# AUTOGENERATED from nimble.lock — do not edit manually.
# Regenerate with: ./tools/gen-nix-deps.sh nimble.lock nix/deps.nix
{ pkgs }:

{
  unittest2 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-unittest2";
    rev = "26f2ef3ae0ec72a2a75bfe557e02e88f6a31c189";
    sha256 = "1n8n36kad50m97b64y7bzzknz9n7szffxhp0bqpk3g2v7zpda8sw";
    fetchSubmodules = true;
  };

  bearssl = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-bearssl";
    rev = "22c6a76ce015bc07e011562bdcfc51d9446c1e82";
    sha256 = "1cvdd7lfrpa6asmc39al3g4py5nqhpqmvypc36r5qyv7p5arc8a3";
    fetchSubmodules = true;
  };

  bearssl_pkey_decoder = pkgs.fetchgit {
    url = "https://github.com/vacp2p/bearssl_pkey_decoder";
    rev = "21dd3710df9345ed2ad8bf8f882761e07863b8e0";
    sha256 = "0bl3f147zmkazbhdkr4cj1nipf9rqiw3g4hh1j424k9hpl55zdpg";
    fetchSubmodules = true;
  };

  jwt = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-jwt.git";
    rev = "057ec95eb5af0eea9c49bfe9025b3312c95dc5f2";
    sha256 = "1hnxsl5762fdn80hl4xxfdqrcgmxrrfck66js1iqaqfxc4m0fv63";
    fetchSubmodules = true;
  };

  testutils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-testutils";
    rev = "6ce5e5e2301ccbc04b09d27ff78741ff4d352b4d";
    sha256 = "1vbkr6i5yxhc2ai3b7rbglhmyc98f99x874fqdp6a152a6kqgwxy";
    fetchSubmodules = true;
  };

  db_connector = pkgs.fetchgit {
    url = "https://github.com/nim-lang/db_connector";
    rev = "29450a2063970712422e1ab857695c12d80112a6";
    sha256 = "11dna09ccdhj3pzpqa04j7a95ibx907z6n1ff33yf0n92qa4x59z";
    fetchSubmodules = true;
  };

  results = pkgs.fetchgit {
    url = "https://github.com/arnetheduck/nim-results";
    rev = "df8113dda4c2d74d460a8fa98252b0b771bf1f27";
    sha256 = "1h7amas16sbhlr7zb7n3jb5434k98ji375vzw72k1fsc86vnmcr9";
    fetchSubmodules = true;
  };

  nat_traversal = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-nat-traversal";
    rev = "860e18c37667b5dd005b94c63264560c35d88004";
    sha256 = "0319k5bbl468phwfnvlrh7725sc80rnf7m9gyj0i3cb5hb9q78bs";
    fetchSubmodules = true;
  };

  stew = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-stew";
    rev = "4382b18f04b3c43c8409bfcd6b62063773b2bbaa";
    sha256 = "0mx9g5m636h3sk5pllcpylk51brf7lx91izx3gc23k3ih3hrxyk2";
    fetchSubmodules = true;
  };

  zlib = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-zlib";
    rev = "e680f269fb01af2c34a2ba879ff281795a5258fe";
    sha256 = "1xw9f1gjsgqihdg7kdkbaq1wankgnx2vn9l3ihc6nqk2jzv5bvk5";
    fetchSubmodules = true;
  };

  httputils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-http-utils";
    rev = "f142cb2e8bd812dd002a6493b6082827bb248592";
    sha256 = "03msj4zdxraz4qx9cidb17g7v0asazxv91nng6xxbzjxz0qaqxw6";
    fetchSubmodules = true;
  };

  chronos = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronos";
    rev = "45f43a9ad8bd8bcf5903b42f365c1c879bd54240";
    sha256 = "1v1n59zfzznp97pvwgs9kf136bqmv4x2s2y9f24msspa7qv27w39";
    fetchSubmodules = true;
  };

  metrics = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-metrics";
    rev = "a1296caf3ebb5f30f51a5feae7749a30df2824c2";
    sha256 = "02vxqy20g8012ks939ac25ksc25k727q84si0p2cmihy5bw1a3qm";
    fetchSubmodules = true;
  };

  faststreams = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-faststreams";
    rev = "ce27581a3e881f782f482cb66dc5b07a02bd615e";
    sha256 = "0y6bw2scnmr8cxj4fg18w7f34l2bh9qwg5nhlgd84m9fpr5bqarn";
    fetchSubmodules = true;
  };

  snappy = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-snappy";
    rev = "00bfcef94f8ef6981df5d5b994897f6695badfb2";
    sha256 = "117mam97mkjjj1hs8svc07679k5ayww9yigi74yq8dyqm6fpbl6l";
    fetchSubmodules = true;
  };

  serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-serialization";
    rev = "b0f2fa32960ea532a184394b0f27be37bd80248b";
    sha256 = "0wip1fjx7ka39ck1g1xvmyarzq1p5dlngpqil6zff8k8z5skiz27";
    fetchSubmodules = true;
  };

  toml_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-toml-serialization";
    rev = "b5b387e6fb2a7cc75d54a269b07cc6218361bd46";
    sha256 = "175swdj01rz57h1hvflkyaz4x76qbfn0174ysrk3qk385i1zlg5z";
    fetchSubmodules = true;
  };

  confutils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-confutils";
    rev = "36f3115ca350f40841ac0eecc7dfa5fe7790c864";
    sha256 = "1vppqplwlpl7a61r8iki5hlzvhd8lnq41ixpqslv35dnm482c55j";
    fetchSubmodules = true;
  };

  cbor_serialization = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-cbor-serialization";
    rev = "1664160e04d153573373afddc552b9cbf6fbe4dc";
    sha256 = "0c1rj4fk0fcqvsf0yqhxvm8h10aww75gi4yfsjhlczh88ypywii2";
    fetchSubmodules = true;
  };

  json_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-json-serialization";
    rev = "c343b0e243d9e17e2c40f3a8a24340f7c4a71d44";
    sha256 = "0i8sq51nqj8lshf6bfixaz9a7sq0ahsbvq3chkxdvv4khsqvam91";
    fetchSubmodules = true;
  };

  chronicles = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronicles";
    rev = "27ec507429a4eb81edc20f28292ee8ec420be05b";
    sha256 = "1xx9fcfwgcaizq3s7i3s03mclz253r5j8va38l9ycl19fcbc96z9";
    fetchSubmodules = true;
  };

  presto = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-presto";
    rev = "d66043dd7ede146442e6c39720c76a20bde5225f";
    sha256 = "1hrppcak32aigrdv3mqk124w81yy9jv1prs57vqqhfj83gl930vi";
    fetchSubmodules = true;
  };

  brokers = pkgs.fetchgit {
    url = "https://github.com/NagyZoltanPeter/nim-brokers.git";
    rev = "a7316a35f1b62e3497ae8ee0fc1aace74df0beb2";
    sha256 = "1990270n88jm0i48g07zr4vq2nn79g7gymf28f3g5ak42g33l7rm";
    fetchSubmodules = true;
  };

  stint = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-stint";
    rev = "470b7892561b5179ab20bd389a69217d6213fe58";
    sha256 = "1isfwmbj98qfi5pm9acy0yyvq0vlz38nxp30xl43jx2mmaga2w22";
    fetchSubmodules = true;
  };

  minilru = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-minilru";
    rev = "6dd93feb60f4cded3c05e7af7209cf63fb677893";
    sha256 = "1xgx4j56ais3hk8b51zhnfs9q85g2afkp3y1j9ky5iziqvcs2sml";
    fetchSubmodules = true;
  };

  sqlite3_abi = pkgs.fetchgit {
    url = "https://github.com/arnetheduck/nim-sqlite3-abi";
    rev = "8240e8e2819dfce1b67fa2733135d01b5cc80ae0";
    sha256 = "0g8bc0kiwxxh3h5w06ksa23cw81hnx87rdn93v64m2f053nb6bcm";
    fetchSubmodules = true;
  };

  dnsclient = pkgs.fetchgit {
    url = "https://github.com/ba0f3/dnsclient.nim";
    rev = "23214235d4784d24aceed99bbfe153379ea557c8";
    sha256 = "03mf3lw5c0m5nq9ppa49nylrl8ibkv2zzlc0wyhqg7w09kz6hks6";
    fetchSubmodules = true;
  };

  unicodedb = pkgs.fetchgit {
    url = "https://github.com/nitely/nim-unicodedb";
    rev = "66f2458710dc641dd4640368f9483c8a0ec70561";
    sha256 = "092z3glgdb7rmwajm7dmqzvralkm7ixighixk8ycf8sf17zm72ck";
    fetchSubmodules = true;
  };

  regex = pkgs.fetchgit {
    url = "https://github.com/nitely/nim-regex";
    rev = "4593305ed1e49731fc75af1dc572dd2559aad19c";
    sha256 = "1b666qws5sva3n5allin0ycvnqlzdjd7xzprpdvv632ccqddzcl9";
    fetchSubmodules = true;
  };

  nimcrypto = pkgs.fetchgit {
    url = "https://github.com/cheatfate/nimcrypto";
    rev = "721fb99ee099b632eb86dfad1f0d96ee87583774";
    sha256 = "178vzb3q8wzjq295ik2pd25rrqf32w381ck76hm5x2d8qnzfmkkc";
    fetchSubmodules = true;
  };

  websock = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-websock";
    rev = "387a8eb7e961e8fdd3b1a717d36bc53b55e4dc5d";
    sha256 = "1v0m3x96fbp9jdzsys6mbxxc2xw3k3dqiv7wksfla89gc6z8w377";
    fetchSubmodules = true;
  };

  json_rpc = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-json-rpc.git";
    rev = "6f1fff8ba685c9192fab153a9d66484ad9066e78";
    sha256 = "1r4xlis5fxcmp1cdqskb25nzmxckfkl8lndshvl76kcqrb0hl88d";
    fetchSubmodules = true;
  };

  lsquic = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-lsquic";
    rev = "2f01046bf1d513de8b5f8296c3d8bec819ab0cb9";
    sha256 = "16xj0hx13nc95x7scck8lyir0kzx4wqnd6d4h79aai8j9hlcmbsl";
    fetchSubmodules = true;
  };

  secp256k1 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-secp256k1";
    rev = "d8f1288b7c72f00be5fc2c5ea72bf5cae1eafb15";
    sha256 = "1qjrmwbngb73f6r1fznvig53nyal7wj41d1cmqfksrmivk2sgrn2";
    fetchSubmodules = true;
  };

  eth = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-eth";
    rev = "d9135e6c3c5d6d819afdfb566aa8d958756b73a8";
    sha256 = "15r6aszalnbk6mkyfbv5rnz5vcf1mmgj6yg332wry53xsd2ipg7r";
    fetchSubmodules = true;
  };

  web3 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-web3";
    rev = "cdfe5601d2812a58e54faf53ee634452d01e5918";
    sha256 = "1j52vcqw868qs40bh4wzfw5cvvnywp2q0dnzhfajh31xws98jc27";
    fetchSubmodules = true;
  };

  dnsdisc = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-dnsdisc";
    rev = "38f2e0f52c0a8f032ef4530835e519d550706d9e";
    sha256 = "0dk787ny49n41bmzhlrvm87giwajr01gwdw9nlmphch89rdqpxxn";
    fetchSubmodules = true;
  };

  libp2p = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-libp2p.git";
    rev = "c43199378f46d0aaf61be1cad1ee1d63e8f665d6";
    sha256 = "0q1hkwwz08zfdwwz7cfql1hqil0iyv3dn8jypdwqmg7497l1bmxk";
    fetchSubmodules = true;
  };

  taskpools = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-taskpools";
    rev = "9e8ccc754631ac55ac2fd495e167e74e86293edb";
    sha256 = "1y78l33vdjxmb9dkr455pbphxa73rgdsh8m9gpkf4d9b1wm1yivy";
    fetchSubmodules = true;
  };

  sds = pkgs.fetchgit {
    # Keep in sync with the nim-sds pin in nimble.lock.
    url = "https://github.com/logos-messaging/nim-sds.git";
    rev = "b12f5ee07c5b764303b51fb948b32a4ade1de3b5";
    sha256 = "1z8f0v1ww7y6zssdacjxfs6s4862dwckw25df3yn1v0qnz40rpc8";
    fetchSubmodules = true;
  };

  ffi = pkgs.fetchgit {
    url = "https://github.com/logos-messaging/nim-ffi";
    rev = "06111de155253b34e47ed2aaed1d61d08d62cc1b";
    sha256 = "0rb0d2i519amgsp7q0bn6m5465z1vwj4rab89529pyiivh3fgh8j";
    fetchSubmodules = true;
  };

  boringssl = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-boringssl";
    rev = "e77caabae78fbc9aa5b78a0a521181b077c82571";
    sha256 = "15k4dqh1hlcpq9zm30lpr728h7apdmgm22xzqhdm3clq9kia6fr8";
    fetchSubmodules = true;
  };

  protobuf_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-protobuf-serialization";
    rev = "38d24eb3bd93e605fb88199da71d36b1ec0ad60d";
    sha256 = "0jr0a41b4r444si6xfa7bclw8mjsk6id10lrdvbxzp99750zspb9";
    fetchSubmodules = true;
  };

  npeg = pkgs.fetchgit {
    url = "https://github.com/zevv/npeg";
    rev = "409f6796d0e880b3f0222c964d1da7de6e450811";
    sha256 = "1h2f5znbpa3svk7wsw2axn8f7f59d23xq85z148kiv6fqh0ffwbm";
    fetchSubmodules = true;
  };

  libp2p_mix = pkgs.fetchgit {
    url = "https://github.com/logos-co/nim-libp2p-mix.git";
    rev = "50c4ab4fa788a33eb12a0a2cecaa708873352b58";
    sha256 = "16prk6cqhalzsvh9kaif5cdn1yadssx3h4572j58fsgm20kdrala";
    fetchSubmodules = true;
  };

  mix_rln_spam_protection = pkgs.fetchgit {
    url = "https://github.com/logos-co/mix-rln-spam-protection-plugin.git";
    rev = "61ee3e5aacb6b224b70e164ef7d0a5714fe66b26";
    sha256 = "0j68v3a8vwrrdpcfmabzdlx867nh4lf9flxvfrzq3xs03m2si57h";
    fetchSubmodules = true;
  };

}
