# AUTOGENERATED from nimble.lock — do not edit manually.
# Regenerate with: ./tools/gen-nix-deps.sh nimble.lock nix/deps.nix
{ pkgs }:

{
  npeg = pkgs.fetchgit {
    url = "https://github.com/zevv/npeg";
    rev = "409f6796d0e880b3f0222c964d1da7de6e450811";
    sha256 = "1h2f5znbpa3svk7wsw2axn8f7f59d23xq85z148kiv6fqh0ffwbm";
    fetchSubmodules = true;
  };

  results = pkgs.fetchgit {
    url = "https://github.com/arnetheduck/nim-results";
    rev = "df8113dda4c2d74d460a8fa98252b0b771bf1f27";
    sha256 = "1h7amas16sbhlr7zb7n3jb5434k98ji375vzw72k1fsc86vnmcr9";
    fetchSubmodules = true;
  };

  nat_traversal = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-nat-traversal";
    rev = "860e18c37667b5dd005b94c63264560c35d88004";
    sha256 = "0319k5bbl468phwfnvlrh7725sc80rnf7m9gyj0i3cb5hb9q78bs";
    fetchSubmodules = true;
  };

  unicodedb = pkgs.fetchgit {
    url = "https://github.com/nitely/nim-unicodedb";
    rev = "b70aac15a3fdc7647997bd6cd10bccd8b2c00e54";
    sha256 = "00z5z1m14gw266ld7yy3gvnm08d1kgij66cg4h76yllkc1k1xk0s";
    fetchSubmodules = true;
  };

  regex = pkgs.fetchgit {
    url = "https://github.com/nitely/nim-regex";
    rev = "4593305ed1e49731fc75af1dc572dd2559aad19c";
    sha256 = "1b666qws5sva3n5allin0ycvnqlzdjd7xzprpdvv632ccqddzcl9";
    fetchSubmodules = true;
  };

  boringssl = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-boringssl";
    rev = "346429e4cda48e775f2d1eb3ccb8757edf4f3648";
    sha256 = "0x46sdq75zp84qahwh472qr33xw38adrsp41fksh7xwwd6384fl3";
    fetchSubmodules = true;
  };

  unittest2 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-unittest2.git";
    rev = "26f2ef3ae0ec72a2a75bfe557e02e88f6a31c189";
    sha256 = "1n8n36kad50m97b64y7bzzknz9n7szffxhp0bqpk3g2v7zpda8sw";
    fetchSubmodules = true;
  };

  testutils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-testutils";
    rev = "6ce5e5e2301ccbc04b09d27ff78741ff4d352b4d";
    sha256 = "1vbkr6i5yxhc2ai3b7rbglhmyc98f99x874fqdp6a152a6kqgwxy";
    fetchSubmodules = true;
  };

  intops = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-intops";
    rev = "ade5d78d60124d1fd50d2109c5eb9416ed147231";
    sha256 = "1q0dg49g8m99m3vrmxxqqhlci62y0mihlp8aq1ssm19597kpvjhz";
    fetchSubmodules = true;
  };

  bearssl = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-bearssl";
    rev = "b6c9a38964a574f6bc51f69efaf8fb2fedea905e";
    sha256 = "0cv4g2l1pk97qgyy53nqyabpnayr8qx6fw35vjs08zs6af05c4fm";
    fetchSubmodules = true;
  };

  bearssl_pkey_decoder = pkgs.fetchgit {
    url = "https://github.com/vacp2p/bearssl_pkey_decoder";
    rev = "d34aa46bf9d0a3ffff810fbd3c4d2fa024eb9368";
    sha256 = "0200f7lf3x2hypwr2v9gms6qv7wj8m1phwd25025bfa1w9f2nkbg";
    fetchSubmodules = true;
  };

  jwt = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-jwt.git";
    rev = "057ec95eb5af0eea9c49bfe9025b3312c95dc5f2";
    sha256 = "1hnxsl5762fdn80hl4xxfdqrcgmxrrfck66js1iqaqfxc4m0fv63";
    fetchSubmodules = true;
  };

  stew = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-stew";
    rev = "c75502ceedb5ed2a37b7b5e4744fc71313682859";
    sha256 = "10vvsghdchwphpwaqzmjixp01645ki5z5fk225f0i3742hpm6xk4";
    fetchSubmodules = true;
  };

  zlib = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-zlib";
    rev = "190246aa0bb6569781370964fa2faa474203d6dd";
    sha256 = "0x5l55gwzb1ay3k9inmi1g25jiv7flry247fcwd8rw3zw9pgchfv";
    fetchSubmodules = true;
  };

  httputils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-http-utils";
    rev = "7d771ca337bd3bf563f6834569d2a06085ac21f1";
    sha256 = "0s4pa0g50kmnzl6151pxzil0w0324l0nvfyfbjgvcn0lyflrxjaw";
    fetchSubmodules = true;
  };

  chronos = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronos";
    rev = "90f543e447f6ade46f028bd7bdf882ae7fcb0ba9";
    sha256 = "0grbkcr4whiadzcszx84ch4mpa71hhr77n3z0dlzyb4d4iykj6cr";
    fetchSubmodules = true;
  };

  libplum = pkgs.fetchgit {
    url = "https://github.com/logos-storage/nim-libplum";
    rev = "189a4984d15f0c60780d6ea5a2ab46bbf6a350f8";
    sha256 = "0nllnpl4mdi58hla0hmx35bkbjmvz4q79wbdmz01vg3qwdnq1r50";
    fetchSubmodules = true;
  };

  metrics = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-metrics";
    rev = "9f2e1d4a4164deb37603b16cedd1707408ee5955";
    sha256 = "05fwkysgj1q3p9ya15pl48nkvl5jv43bmrrkg70z7b6may6fgvqj";
    fetchSubmodules = true;
  };

  faststreams = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-faststreams";
    rev = "059bc2f52546ac14b583639c33372c14b1d46fa3";
    sha256 = "0xmma6a1b5lgzfqnk1vq3hvf8klbhcab0fnzz4xb68mpdrgvlvk4";
    fetchSubmodules = true;
  };

  snappy = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-snappy";
    rev = "da2f0c7b6ce9053106e9bb098204fe5319038387";
    sha256 = "1jmjh1b70wkhzmyzvp46y50x3i1f0hkdrpy6msvqix60xwkxf1zy";
    fetchSubmodules = true;
  };

  serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-serialization";
    rev = "b5473564e80a4908cf6c5a038e4c4a6ca7de2223";
    sha256 = "09abpya7mvcaymxf0n2sc122rq4jkwg9kpis8xyc4z3fx3x3znxk";
    fetchSubmodules = true;
  };

  protobuf_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-protobuf-serialization";
    rev = "a671c6d497c7028ed7390b2d5a80c7b62138c586";
    sha256 = "1i7nid50smfmxvc0zc5cp2xd227ll11r7y261bbj769gpd9bz0ax";
    fetchSubmodules = true;
  };

  toml_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-toml-serialization";
    rev = "b5b387e6fb2a7cc75d54a269b07cc6218361bd46";
    sha256 = "175swdj01rz57h1hvflkyaz4x76qbfn0174ysrk3qk385i1zlg5z";
    fetchSubmodules = true;
  };

  confutils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-confutils";
    rev = "cdbac612f0f3d2883e959807d790658854e73cf2";
    sha256 = "0p0yws752k72hc0g1lz6a4nz5n5nnbpipy7sxvnmg80dd6hb4xj8";
    fetchSubmodules = true;
  };

  cbor_serialization = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-cbor-serialization";
    rev = "1664160e04d153573373afddc552b9cbf6fbe4dc";
    sha256 = "0c1rj4fk0fcqvsf0yqhxvm8h10aww75gi4yfsjhlczh88ypywii2";
    fetchSubmodules = true;
  };

  json_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-json-serialization";
    rev = "73c37b46591cf3d6a19d39ff0ed14b2e77433778";
    sha256 = "0fk01rscd5kwdvgv2g3r3wdgbh1cliyjkgdmxc25k11lbkzyp0dl";
    fetchSubmodules = true;
  };

  chronicles = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronicles";
    rev = "45c823b8af409f82fa35fd5e1f6a7c9a06fe3137";
    sha256 = "1pl3cs6v4b4l3jk7kifni7sc7jn64alpbkwlh12vwd78knqkqmhf";
    fetchSubmodules = true;
  };

  presto = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-presto";
    rev = "e07ae5ddfe6ae17e238a0cd7a366e1ee6886bec0";
    sha256 = "1hr4w2qm0pp3r63h4rpgsc450ghrvqx817qs1x1c0bnncwgalhkz";
    fetchSubmodules = true;
  };

  brokers = pkgs.fetchgit {
    url = "https://github.com/NagyZoltanPeter/nim-brokers.git";
    rev = "19565dd80621e33f6da396ef3fb07c379d55c324";
    sha256 = "0jnn44pk587ck1l3ghjgy93d32fpxf0bjshri5ksnqjif2b7pdm9";
    fetchSubmodules = true;
  };

  stint = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-stint";
    rev = "273fcdfa8dce4ceb975b383ffafe5e79e82766e2";
    sha256 = "0a82y2c3s8bfzvaz8bpcfdn22xy79cqzhrkrncbb70lkdnnsyd4h";
    fetchSubmodules = true;
  };

  taskpools = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-taskpools";
    rev = "7d96007793fdb2d244d392eb7c5cfa4a695d4ecc";
    sha256 = "0qi2kf1lj5ki101whjq68k5l00hh1vrz3izp2riv9q29zicwczyc";
    fetchSubmodules = true;
  };

  ffi = pkgs.fetchgit {
    url = "https://github.com/logos-messaging/nim-ffi";
    rev = "07ee8e1d6500762bab290465457a8d23559de546";
    sha256 = "04q5gmldyxd8jawrnjfws007zpyr4h08ijphp943iypbpblflfmz";
    fetchSubmodules = true;
  };

  minilru = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-minilru";
    rev = "6a6929edaf365bf032f00e5cd197d0eeb7a0467e";
    sha256 = "0zbpqb4iixgk2fs5bw56m9zjzyb7q42gj4ps53bvgw3hzcy48zhb";
    fetchSubmodules = true;
  };

  db_connector = pkgs.fetchgit {
    url = "https://github.com/nim-lang/db_connector";
    rev = "29450a2063970712422e1ab857695c12d80112a6";
    sha256 = "11dna09ccdhj3pzpqa04j7a95ibx907z6n1ff33yf0n92qa4x59z";
    fetchSubmodules = true;
  };

  sqlite3_abi = pkgs.fetchgit {
    url = "https://github.com/arnetheduck/nim-sqlite3-abi";
    rev = "9645cad7f8c6d27a322ef48a60722a3f88f44c27";
    sha256 = "0vy8viiqbpf28pqy5s515qfsc0ygxxishmyz56xjqa29l3qslqjk";
    fetchSubmodules = true;
  };

  dnsclient = pkgs.fetchgit {
    url = "https://github.com/ba0f3/dnsclient.nim";
    rev = "23214235d4784d24aceed99bbfe153379ea557c8";
    sha256 = "03mf3lw5c0m5nq9ppa49nylrl8ibkv2zzlc0wyhqg7w09kz6hks6";
    fetchSubmodules = true;
  };

  nimcrypto = pkgs.fetchgit {
    url = "https://github.com/cheatfate/nimcrypto";
    rev = "721fb99ee099b632eb86dfad1f0d96ee87583774";
    sha256 = "178vzb3q8wzjq295ik2pd25rrqf32w381ck76hm5x2d8qnzfmkkc";
    fetchSubmodules = true;
  };

  lsquic = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-lsquic";
    rev = "07783b55fb0ee7e9dc2dd9ced11548f84174306e";
    sha256 = "1jw7dry32k49hb66vlwvm4q7404qcc257gvkj1xh5afwjxry14rs";
    fetchSubmodules = true;
  };

  websock = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-websock";
    rev = "387a8eb7e961e8fdd3b1a717d36bc53b55e4dc5d";
    sha256 = "1v0m3x96fbp9jdzsys6mbxxc2xw3k3dqiv7wksfla89gc6z8w377";
    fetchSubmodules = true;
  };

  json_rpc = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-json-rpc";
    rev = "6f1fff8ba685c9192fab153a9d66484ad9066e78";
    sha256 = "1r4xlis5fxcmp1cdqskb25nzmxckfkl8lndshvl76kcqrb0hl88d";
    fetchSubmodules = true;
  };

  secp256k1 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-secp256k1";
    rev = "d8f1288b7c72f00be5fc2c5ea72bf5cae1eafb15";
    sha256 = "1qjrmwbngb73f6r1fznvig53nyal7wj41d1cmqfksrmivk2sgrn2";
    fetchSubmodules = true;
  };

  libp2p = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-libp2p";
    rev = "391e403cc274ab8623fb1106f2c2827e09c6c89f";
    sha256 = "04hn4q73c598hh8hxs9y1s3zq6zhijb74776z23q4adlymy15x5q";
    fetchSubmodules = true;
  };

  sds = pkgs.fetchgit {
    url = "https://github.com/logos-messaging/nim-sds.git";
    rev = "b12f5ee07c5b764303b51fb948b32a4ade1de3b5";
    sha256 = "1z8f0v1ww7y6zssdacjxfs6s4862dwckw25df3yn1v0qnz40rpc8";
    fetchSubmodules = true;
  };

  libp2p_mix = pkgs.fetchgit {
    url = "https://github.com/logos-co/nim-libp2p-mix";
    rev = "39d2ac78da7b7f33562eb7cd95d6280ca9fa0e94";
    sha256 = "098db702wviph33mzvlj4b20cpj10csfya2yx80rwlppc2brxqc4";
    fetchSubmodules = true;
  };

  eth = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-eth";
    rev = "d9135e6c3c5d6d819afdfb566aa8d958756b73a8";
    sha256 = "15r6aszalnbk6mkyfbv5rnz5vcf1mmgj6yg332wry53xsd2ipg7r";
    fetchSubmodules = true;
  };

  web3 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-web3";
    rev = "cdfe5601d2812a58e54faf53ee634452d01e5918";
    sha256 = "1j52vcqw868qs40bh4wzfw5cvvnywp2q0dnzhfajh31xws98jc27";
    fetchSubmodules = true;
  };

  dnsdisc = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-dnsdisc";
    rev = "6cb1b7e3922645275043c68e476cac1501a45e55";
    sha256 = "02vxprjw4ixicdfczznns62izys9jgmsvy28rzlfd0wqg79gn9mc";
    fetchSubmodules = true;
  };

}
