# AUTOGENERATED from nimble.lock — do not edit manually.
# Regenerate with: ./tools/gen-nix-deps.sh nimble.lock nix/deps.nix
{ pkgs }:

{
  libbacktrace = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-libbacktrace";
    rev = "ebc972d99769633b9ef3ee766778ee5aa1996499";
    sha256 = "192wwixwp36r6wiq495d7yr3nbskay75447p99snqq359bqv9snb";
    fetchSubmodules = true;
  };

  npeg = pkgs.fetchgit {
    url = "https://github.com/zevv/npeg";
    rev = "409f6796d0e880b3f0222c964d1da7de6e450811";
    sha256 = "1h2f5znbpa3svk7wsw2axn8f7f59d23xq85z148kiv6fqh0ffwbm";
    fetchSubmodules = true;
  };

  results = pkgs.fetchgit {
    url = "https://github.com/arnetheduck/nim-results";
    rev = "df8113dda4c2d74d460a8fa98252b0b771bf1f27";
    sha256 = "1h7amas16sbhlr7zb7n3jb5434k98ji375vzw72k1fsc86vnmcr9";
    fetchSubmodules = true;
  };

  nat_traversal = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-nat-traversal";
    rev = "860e18c37667b5dd005b94c63264560c35d88004";
    sha256 = "0319k5bbl468phwfnvlrh7725sc80rnf7m9gyj0i3cb5hb9q78bs";
    fetchSubmodules = true;
  };

  unicodedb = pkgs.fetchgit {
    url = "https://github.com/nitely/nim-unicodedb";
    rev = "66f2458710dc641dd4640368f9483c8a0ec70561";
    sha256 = "092z3glgdb7rmwajm7dmqzvralkm7ixighixk8ycf8sf17zm72ck";
    fetchSubmodules = true;
  };

  regex = pkgs.fetchgit {
    url = "https://github.com/nitely/nim-regex";
    rev = "4593305ed1e49731fc75af1dc572dd2559aad19c";
    sha256 = "1b666qws5sva3n5allin0ycvnqlzdjd7xzprpdvv632ccqddzcl9";
    fetchSubmodules = true;
  };

  boringssl = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-boringssl";
    rev = "e77caabae78fbc9aa5b78a0a521181b077c82571";
    sha256 = "15k4dqh1hlcpq9zm30lpr728h7apdmgm22xzqhdm3clq9kia6fr8";
    fetchSubmodules = true;
  };

  unittest2 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-unittest2.git";
    rev = "26f2ef3ae0ec72a2a75bfe557e02e88f6a31c189";
    sha256 = "1n8n36kad50m97b64y7bzzknz9n7szffxhp0bqpk3g2v7zpda8sw";
    fetchSubmodules = true;
  };

  bearssl = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-bearssl";
    rev = "7c307026d4d86dc560880c6fa716f5e626ff7fc2";
    sha256 = "0ifi3vy48j0vfwqjhm4xsik5i8k7xi33cmhvzx2aklj8a2a83avn";
    fetchSubmodules = true;
  };

  bearssl_pkey_decoder = pkgs.fetchgit {
    url = "https://github.com/vacp2p/bearssl_pkey_decoder";
    rev = "d34aa46bf9d0a3ffff810fbd3c4d2fa024eb9368";
    sha256 = "0200f7lf3x2hypwr2v9gms6qv7wj8m1phwd25025bfa1w9f2nkbg";
    fetchSubmodules = true;
  };

  jwt = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-jwt.git";
    rev = "057ec95eb5af0eea9c49bfe9025b3312c95dc5f2";
    sha256 = "1hnxsl5762fdn80hl4xxfdqrcgmxrrfck66js1iqaqfxc4m0fv63";
    fetchSubmodules = true;
  };

  stew = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-stew";
    rev = "4382b18f04b3c43c8409bfcd6b62063773b2bbaa";
    sha256 = "0mx9g5m636h3sk5pllcpylk51brf7lx91izx3gc23k3ih3hrxyk2";
    fetchSubmodules = true;
  };

  testutils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-testutils";
    rev = "74588b8b55d116ca057431ae3a0ca359e0825fcd";
    sha256 = "1bn4v2f8ppknslihdnvlzr0fkm6nlkdim66m8frw4nfyd8jnw7sn";
    fetchSubmodules = true;
  };

  zlib = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-zlib";
    rev = "190246aa0bb6569781370964fa2faa474203d6dd";
    sha256 = "0x5l55gwzb1ay3k9inmi1g25jiv7flry247fcwd8rw3zw9pgchfv";
    fetchSubmodules = true;
  };

  httputils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-http-utils";
    rev = "a9ca86095e262251d8ebafa1c6504fd476c41e43";
    sha256 = "06qiw3zn9gzskp83mn225bvnd2ajc4n0m30x9msljy5p2nn4zjw1";
    fetchSubmodules = true;
  };

  chronos = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronos";
    rev = "447b3fd8ae0619e847bff46d823d56779e21851b";
    sha256 = "1labwbmdmpf49v10k6rjgkgicxdx0zjf5zk3sdzj1mc0wavgz16r";
    fetchSubmodules = true;
  };

  metrics = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-metrics";
    rev = "9f2e1d4a4164deb37603b16cedd1707408ee5955";
    sha256 = "05fwkysgj1q3p9ya15pl48nkvl5jv43bmrrkg70z7b6may6fgvqj";
    fetchSubmodules = true;
  };

  faststreams = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-faststreams";
    rev = "50889cd16ec8771106cdd0eeea460039e8571e06";
    sha256 = "1hd4bhvw5lzwg924i8dif5mi61h0ayiplq38djvrdbfsjdhw2zvw";
    fetchSubmodules = true;
  };

  snappy = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-snappy";
    rev = "00bfcef94f8ef6981df5d5b994897f6695badfb2";
    sha256 = "117mam97mkjjj1hs8svc07679k5ayww9yigi74yq8dyqm6fpbl6l";
    fetchSubmodules = true;
  };

  serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-serialization";
    rev = "4092500cea76154576539371709ae801afbd2a9d";
    sha256 = "04pz6d6p3nd1y2khbb667fcd6p2jk4bxv65iaffzq06bqqhalcwc";
    fetchSubmodules = true;
  };

  protobuf_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-protobuf-serialization";
    rev = "8406e7287196661614ce6a8e8be20f755376af7f";
    sha256 = "0lb4756a77vr1x1khy3dxl97kyxy7w09ap92ylkkgjp093dic59k";
    fetchSubmodules = true;
  };

  toml_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-toml-serialization";
    rev = "b5b387e6fb2a7cc75d54a269b07cc6218361bd46";
    sha256 = "175swdj01rz57h1hvflkyaz4x76qbfn0174ysrk3qk385i1zlg5z";
    fetchSubmodules = true;
  };

  confutils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-confutils";
    rev = "7728f6bd81a1eedcfe277d02ea85fdb805bcc05a";
    sha256 = "18bj1ilx10jm2vmqx2wy2xl9rzy7alymi2m4n9jgpa4sbxnfh0x3";
    fetchSubmodules = true;
  };

  cbor_serialization = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-cbor-serialization";
    rev = "e32d61c54f69b396f47645f9b7373ea2e149013a";
    sha256 = "0vdmvzfrw4p14ybm5ryci69nldk44r0ghfq99bdh1jdrjjki1yrl";
    fetchSubmodules = true;
  };

  json_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-json-serialization";
    rev = "c343b0e243d9e17e2c40f3a8a24340f7c4a71d44";
    sha256 = "0i8sq51nqj8lshf6bfixaz9a7sq0ahsbvq3chkxdvv4khsqvam91";
    fetchSubmodules = true;
  };

  chronicles = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronicles";
    rev = "27ec507429a4eb81edc20f28292ee8ec420be05b";
    sha256 = "1xx9fcfwgcaizq3s7i3s03mclz253r5j8va38l9ycl19fcbc96z9";
    fetchSubmodules = true;
  };

  presto = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-presto";
    rev = "d66043dd7ede146442e6c39720c76a20bde5225f";
    sha256 = "1hrppcak32aigrdv3mqk124w81yy9jv1prs57vqqhfj83gl930vi";
    fetchSubmodules = true;
  };

  brokers = pkgs.fetchgit {
    url = "https://github.com/NagyZoltanPeter/nim-brokers.git";
    rev = "19565dd80621e33f6da396ef3fb07c379d55c324";
    sha256 = "0jnn44pk587ck1l3ghjgy93d32fpxf0bjshri5ksnqjif2b7pdm9";
    fetchSubmodules = true;
  };

  stint = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-stint";
    rev = "470b7892561b5179ab20bd389a69217d6213fe58";
    sha256 = "1isfwmbj98qfi5pm9acy0yyvq0vlz38nxp30xl43jx2mmaga2w22";
    fetchSubmodules = true;
  };

  minilru = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-minilru";
    rev = "6dd93feb60f4cded3c05e7af7209cf63fb677893";
    sha256 = "1xgx4j56ais3hk8b51zhnfs9q85g2afkp3y1j9ky5iziqvcs2sml";
    fetchSubmodules = true;
  };

  db_connector = pkgs.fetchgit {
    url = "https://github.com/nim-lang/db_connector";
    rev = "29450a2063970712422e1ab857695c12d80112a6";
    sha256 = "11dna09ccdhj3pzpqa04j7a95ibx907z6n1ff33yf0n92qa4x59z";
    fetchSubmodules = true;
  };

  sqlite3_abi = pkgs.fetchgit {
    url = "https://github.com/arnetheduck/nim-sqlite3-abi";
    rev = "a4d052efe81472b8d5271ece8e5a3caea90a45eb";
    sha256 = "0bndp3dq41m9m63kgspqjkwq9z2pjcgcm93zkhnyrv66dnp2g40b";
    fetchSubmodules = true;
  };

  dnsclient = pkgs.fetchgit {
    url = "https://github.com/ba0f3/dnsclient.nim";
    rev = "23214235d4784d24aceed99bbfe153379ea557c8";
    sha256 = "03mf3lw5c0m5nq9ppa49nylrl8ibkv2zzlc0wyhqg7w09kz6hks6";
    fetchSubmodules = true;
  };

  nimcrypto = pkgs.fetchgit {
    url = "https://github.com/cheatfate/nimcrypto";
    rev = "721fb99ee099b632eb86dfad1f0d96ee87583774";
    sha256 = "178vzb3q8wzjq295ik2pd25rrqf32w381ck76hm5x2d8qnzfmkkc";
    fetchSubmodules = true;
  };

  lsquic = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-lsquic";
    rev = "b778d16d6f00b47249e2674c23f21aa26b711eb7";
    sha256 = "1wn2bcxn4w916kj7lk0hzf7nxi64x75ksfgx77cr0pcnncygbxvk";
    fetchSubmodules = true;
  };

  websock = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-websock";
    rev = "387a8eb7e961e8fdd3b1a717d36bc53b55e4dc5d";
    sha256 = "1v0m3x96fbp9jdzsys6mbxxc2xw3k3dqiv7wksfla89gc6z8w377";
    fetchSubmodules = true;
  };

  json_rpc = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-json-rpc.git";
    rev = "6f1fff8ba685c9192fab153a9d66484ad9066e78";
    sha256 = "1r4xlis5fxcmp1cdqskb25nzmxckfkl8lndshvl76kcqrb0hl88d";
    fetchSubmodules = true;
  };

  secp256k1 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-secp256k1";
    rev = "d8f1288b7c72f00be5fc2c5ea72bf5cae1eafb15";
    sha256 = "1qjrmwbngb73f6r1fznvig53nyal7wj41d1cmqfksrmivk2sgrn2";
    fetchSubmodules = true;
  };

  libp2p = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-libp2p";
    rev = "0e763288c10b6488e5971608f12aa49ab129720e";
    sha256 = "1wqy7zcpjrbf2585jw6rmzd7f9yq0kv9jvhkrg5nq8xaikf6hhb4";
    fetchSubmodules = true;
  };

  libp2p_mix = pkgs.fetchgit {
    url = "https://github.com/logos-co/nim-libp2p-mix";
    rev = "395b65aadf0a4ad273e544647b7e06f1ca77cf67";
    sha256 = "1x8aqm4g42qg9153v4g80msqc95lmginhs2fr1xin9mlfgqza855";
    fetchSubmodules = true;
  };

  eth = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-eth";
    rev = "d9135e6c3c5d6d819afdfb566aa8d958756b73a8";
    sha256 = "15r6aszalnbk6mkyfbv5rnz5vcf1mmgj6yg332wry53xsd2ipg7r";
    fetchSubmodules = true;
  };

  web3 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-web3";
    rev = "cdfe5601d2812a58e54faf53ee634452d01e5918";
    sha256 = "1j52vcqw868qs40bh4wzfw5cvvnywp2q0dnzhfajh31xws98jc27";
    fetchSubmodules = true;
  };

  dnsdisc = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-dnsdisc";
    rev = "6cb1b7e3922645275043c68e476cac1501a45e55";
    sha256 = "02vxprjw4ixicdfczznns62izys9jgmsvy28rzlfd0wqg79gn9mc";
    fetchSubmodules = true;
  };

  taskpools = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-taskpools";
    rev = "9e8ccc754631ac55ac2fd495e167e74e86293edb";
    sha256 = "1y78l33vdjxmb9dkr455pbphxa73rgdsh8m9gpkf4d9b1wm1yivy";
    fetchSubmodules = true;
  };

  ffi = pkgs.fetchgit {
    url = "https://github.com/logos-messaging/nim-ffi";
    rev = "06111de155253b34e47ed2aaed1d61d08d62cc1b";
    sha256 = "0rb0d2i519amgsp7q0bn6m5465z1vwj4rab89529pyiivh3fgh8j";
    fetchSubmodules = true;
  };

  sds = pkgs.fetchgit {
    url = "https://github.com/logos-messaging/nim-sds.git";
    rev = "b12f5ee07c5b764303b51fb948b32a4ade1de3b5";
    sha256 = "1z8f0v1ww7y6zssdacjxfs6s4862dwckw25df3yn1v0qnz40rpc8";
    fetchSubmodules = true;
  };

}
