{
 "title": "logos-messaging-nim-monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values({job=\"postgres-exporter\"}, instance)"
   },
   { "name": "Database", "query": "label_values(datname)" },
   { "name": "Interval", "query": "30sec,1m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Node - Network & Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Times (UTC)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"logos-messaging-node\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "waku_version{instance=\"logos-messaging-node:8003\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discv5 (Nodes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "routing_table_nodes", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "libp2p_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number Pubsub Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "libp2p_pubsub_topics", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Discv5 (Seen Nodes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "routing_table_nodes{state=\"seen\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reachability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_autonat_reachability_confidence",
     "legendFormat": "{{reachability}}"
    }
   ]
  },
  {
   "title": "Connected Peers (Direction/Protocol)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "waku_connected_peers", "legendFormat": "{{direction}}_{{protocol}}" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 5 },
   "targets": [
    { "expr": "libp2p_peers", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Discv5 Discovered Peers Per Shard",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waku_discv5_discovered_per_shard",
     "legendFormat": "shard-{{shard}}"
    }
   ]
  },
  {
   "title": "Connected Peers Per Shard",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "waku_connected_peers_per_shard", "legendFormat": "shard-{{shard}}" }
   ]
  },
  {
   "title": "Connected Peers Per Agent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "waku_connected_peers_per_agent", "legendFormat": "{{agent}}" }
   ]
  },
  { "title": "Node - Relay Traffic ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Average msg size (kBytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "waku_histogram_message_size_sum/waku_histogram_message_size_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message distrubution %/kBytes (Last Hour)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(waku_histogram_message_size_bucket[1h])/scalar(rate(waku_histogram_message_size_count[1h]))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Msg Size (Last Hour)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(waku_histogram_message_size_sum[1h])/rate(waku_histogram_message_size_count[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "75% Percentile (Last hour)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, rate(waku_histogram_message_size_bucket[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99% Percentile (Last Hour)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(waku_histogram_message_size_bucket[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "libp2p traffic (in)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"in\"}[$__rate_interval])*8",
     "legendFormat": "traffic_{{direction}}"
    }
   ]
  },
  {
   "title": "libp2p traffic (out)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"out\"}[$__rate_interval])*8",
     "legendFormat": "traffic_{{direction}}"
    }
   ]
  },
  {
   "title": "Peer Store Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "waku_peer_store_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Protocol request rates",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 4, "x": 17, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(waku_service_requests_total[$__rate_interval])",
     "legendFormat": "{{proto}}/{{state}}"
    }
   ]
  },
  {
   "title": "Relay traffic per shard (in)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(waku_relay_network_bytes_total{direction=\"in\"}[$__rate_interval])*8",
     "legendFormat": "{{topic}}/{{type}}"
    }
   ]
  },
  {
   "title": "Relay traffic per shard (out)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(waku_relay_network_bytes_total{direction=\"out\"}[$__rate_interval])*8",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Non relay protocol traffic (in)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(waku_service_network_bytes_total{direction=\"in\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Non relay protocol traffic (out)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(waku_service_network_bytes_total{direction=\"out\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total Message Bytes Per Shard",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waku_relay_total_msg_bytes_per_shard",
     "legendFormat": "shard-{{shard}}"
    }
   ]
  },
  {
   "title": "Max Message Bytes Per Shard",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waku_relay_max_msg_bytes_per_shard",
     "legendFormat": "shard-{{shard}}"
    }
   ]
  },
  {
   "title": "Avg Message Bytes Per Shard",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waku_relay_avg_msg_bytes_per_shard",
     "legendFormat": "shard-{{shard}}"
    }
   ]
  },
  {
   "title": "Archive Message Per Shard",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waku_archive_messages_per_shard",
     "legendFormat": "shard-{{shard}}"
    }
   ]
  },
  {
   "title": "Total Messages Size On Store Fleet",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waku_relay_fleet_store_msg_size_bytes",
     "legendFormat": "shard-{{shard}}"
    }
   ]
  },
  {
   "title": "Total Message Count On Store Fleet",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waku_relay_fleet_store_msg_count",
     "legendFormat": "shard-{{shard}}"
    }
   ]
  },
  {
   "title": "Heap allocation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Nim Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "nim_gc_mem_bytes{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Stored Message by Content Topic App Name",
   "type": "table",
   "description": "Messages in local database per app name, as extracted from the content topic.",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT REGEXP_REPLACE(contenttopic,'^\\/(.+)\\/(\\d+)\\/(.+)\\/(.+)$','\\1') as \"App name\", COUNT(id), pg_column_size(payload)\nFROM messages\nGROUP BY contenttopic, payload"
    }
   ]
  },
  {
   "title": "RLN Membership Insertion (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "waku_rln_membership_insertion_duration_seconds",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RLN Credentials Import (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 91 },
   "targets": [
    {
     "expr": "waku_rln_membership_credentials_import_duration_seconds",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RLN Registered Memberships",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 91 },
   "targets": [
    {
     "expr": "waku_rln_number_registered_memberships",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RLN Proof Generation (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "waku_rln_proof_generation_duration_seconds",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RLN Proof Verification (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 97 },
   "targets": [
    {
     "expr": "waku_rln_proof_verification_duration_seconds",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Remaining RLN Proofs per epoch",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 97 },
   "targets": [
    {
     "expr": "waku_rln_remaining_proofs_per_epoch",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total Generated RLN Proofs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "waku_rln_total_generated_proofs",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total Verified RLN Proof",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 103 },
   "targets": [
    {
     "expr": "waku_rln_proof_verification_total_total",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RLN Valid Messages ( Total )",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "waku_rln_valid_messages_total_total",
     "legendFormat": "shard-{{shard}}"
    }
   ]
  },
  {
   "title": "RLN Invalid Messages ( Total )",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 109 },
   "targets": [
    {
     "expr": "waku_rln_invalid_messages_total_total",
     "legendFormat": "type-{{type}}"
    }
   ]
  },
  {
   "title": "RLN Spam Messages ( Total )",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 109 },
   "targets": [
    {
     "expr": "waku_rln_spam_messages_total_total",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Node - Store & DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Unique stored messages (Postgres)",
   "type": "timeseries",
   "description": "Number of messages currently stored in the database",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "pg_tb_messages_count{}", "legendFormat": "messages" }
   ]
  },
  {
   "title": "PostgreSQL Version",
   "type": "stat",
   "description": "Source: server_version_num",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 117 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_settings_server_version_num)"
    }
   ]
  },
  {
   "title": "Active clients (Postgres)",
   "type": "stat",
   "description": "Clients executing Statements.\n\nSource: pg_stat_activity",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 117 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\",instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Total database size (Postgres)",
   "type": "stat",
   "description": "Size of all databases in $Instance.\n\nSource: pg_database_size()",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes{instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Postgres start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Replication Lag (Postgres)",
   "type": "stat",
   "description": "Max Replication lag behind master in seconds\n\nOnly available on a standby system.\n\nSource: pg_last_xact_replay_timestamp\n\nUse: pg_stat_replication for Details.",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 123 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_replication_lag{instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Average query runtime (Postgres)",
   "type": "stat",
   "description": "Source: pg_stat_statements.total_time / pg_stat_statements.calls",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 123 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((delta(pg_stat_statements_total_time_seconds{instance=\"$Instance\"}[$Interval])))/sum((delta(pg_stat_statements_calls{instance=\"$Instance\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Connections by database (stacked) (Postgres)",
   "type": "timeseries",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_activity_count{instance=\"$Instance\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transaction rate (Postgres)",
   "type": "stat",
   "description": "Transactions committed + roolback per minute\n\nSource: pg_stat_database,xact_commit + xact_rollback",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 126 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_xact_commit{instance=\"$Instance\"}[$Interval])))+sum((rate(pg_stat_database_xact_rollback{instance=\"$Instance\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Query rate (Postgres)",
   "type": "stat",
   "description": "Statements executed per Minute.\n\nSource: pg_stat_statements.calls",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 126 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_statements_calls{instance=\"$Instance\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Commit Ratio (Postgres)",
   "type": "gauge",
   "description": "Transaction committed vs rollbacked",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_xact_commit{instance=\"$Instance\"})/(sum(pg_stat_database_xact_commit{instance=\"$Instance\"}) + sum(pg_stat_database_xact_rollback{instance=\"$Instance\"}))"
    }
   ]
  },
  {
   "title": "Connections used (Postgres)",
   "type": "gauge",
   "description": "Percentage of max_connections used",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends)/max(pg_settings_max_connections)"
    }
   ]
  },
  {
   "title": "Shared Buffer Hits (Postgres)",
   "type": "gauge",
   "description": "Shared buffer hits vs reads from disc",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})/(sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})+sum(pg_stat_database_blks_read{instance=~\"$Instance\"}))*100"
    }
   ]
  },
  {
   "title": "Messages/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 129 },
   "targets": [
    {
     "expr": "(increase(waku_node_messages_total[1m]))/60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections by state (stacked) (Postgres)",
   "type": "timeseries",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{instance=\"$Instance\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Estimated number of rows (Postgres)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_live_tup{datname=\"postgres\"}",
     "legendFormat": "Live"
    },
    { "expr": "pg_stat_user_tables_n_dead_tup", "legendFormat": "Dead" }
   ]
  },
  {
   "title": "Tuples inserts/updates/deletes (Postgres)",
   "type": "timeseries",
   "description": "Source: pg_stat_database",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_tup_inserted{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_updated{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_deleted{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "Transactions (Postgres)",
   "type": "timeseries",
   "description": "1 Minute rate of transactions committed or rollback.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_xact_commit[$Interval])))",
     "legendFormat": "committed"
    },
    {
     "expr": "sum ((rate(pg_stat_database_xact_rollback[$Interval])))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Tuples fetched/returned (Postgres)",
   "type": "timeseries",
   "description": "Source: pg_stat_database\n\n* tup_fetched: rows needed to satisfy queries\n* tup_returned: rows read/scanned",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_tup_fetched{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_returned{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "I/O Read/Write time (Postgres)",
   "type": "timeseries",
   "description": "* blk_read_time: Time spent reading data file blocks by backends in this database, in milliseconds\n* blk_write_time: Time spent writing data file blocks by backends in this database, in milliseconds\n\ntrack_io_timings needs to be activated",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_blk_read_time{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "sum ((rate(pg_stat_database_blk_write_time{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "blk_read_time"
    }
   ]
  },
  {
   "title": "Deadlocks by database (Postgres)",
   "type": "timeseries",
   "description": "Should be 0 \n\nSource: pg_stat_database\n\nWith log_lock_waits turned on, deadlocks will be logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_database_deadlocks{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Locks by state (Postgres)",
   "type": "timeseries",
   "description": "Source: pg_locks",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{instance=\"$Instance\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Temporary files by database (Postgres)",
   "type": "timeseries",
   "description": "Should be 0. If temporary files are created, it can indicate insufficient work_mem. With log_temp_files the creation of temporary files are logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_database_temp_files{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "# messages per shard",
   "type": "timeseries",
   "description": "Number of messages currently stored in the database",
   "gridPos": { "h": 10, "w": 7, "x": 12, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "pg_tb_stats_messages{}", "legendFormat": "{{ pubsubtopic }}" }
   ]
  },
  {
   "title": "Replication lag (Postgres)",
   "type": "timeseries",
   "description": "Lag behind master in seconds.\n\nOnly available on a standby System.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(pg_replication_lag{instance=\"$Instance\"})",
     "legendFormat": "lag "
    }
   ]
  }
 ]
}