# Dockerfile to build a distributable container image from pre-existing binaries
FROM debian:bookworm-slim AS prod

ARG MAKE_TARGET=logosdeliverynode

LABEL maintainer="vaclav@status.im"
LABEL source="https://github.com/logos-messaging/logos-delivery"
LABEL description="Logos Delivery node"
LABEL commit="unknown"

# DevP2P, LibP2P, and JSON RPC ports
EXPOSE 30303 60000 8545

# Referenced in the binary
RUN apt-get update &&\
    apt-get install -y libpq-dev curl iproute2 wget dnsutils &&\
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy to separate location to accomodate different MAKE_TARGET values
ADD ./build/$MAKE_TARGET /usr/local/bin/

# Copy migration scripts for DB upgrades
ADD ./migrations/ /app/migrations/

# Symlink the built binary under the canonical name
RUN ln -sv /usr/local/bin/$MAKE_TARGET /usr/bin/logosdeliverynode

ENTRYPOINT ["/usr/bin/logosdeliverynode"]

# By default just show help if called without arguments
CMD ["--help"]
