## api_codegen_cmake
## ----------------
## Emits a per-library CMake package next to the generated headers and shared
## library so consumers can do:
##
##   find_package(<lib> CONFIG REQUIRED)
##   target_link_libraries(myapp PRIVATE <lib>::<lib>)        # C consumers
##   target_link_libraries(myapp PRIVATE <lib>::<lib>_cpp)    # C++ consumers
##
## Files written into `outDir`:
##   <lib>Config.cmake          — defines IMPORTED targets
##   <lib>ConfigVersion.cmake   — version compatibility (SameMajorVersion)
##
## The package is fully relocatable: it resolves the shared library and headers
## relative to its own location (`CMAKE_CURRENT_LIST_DIR`), which is the same
## directory the Nim build dropped them into.
##
## CBOR mode adds a header-only jsoncons dependency on the C++ INTERFACE
## target. Consumers can either install jsoncons system-wide or set
## `<LIB>_JSONCONS_INCLUDE_DIR` before `find_package`.

{.push raises: [].}

import std/strutils
import ./api_outdir

{.pop.}

proc generateCMakePackageFiles*(
    outDir: string, libName: string, version: string, cborMode: bool, hasCpp: bool
) {.compileTime, raises: [].} =
  ## Emits <lib>Config.cmake and <lib>ConfigVersion.cmake into `outDir`.
  ensureGeneratedOutputDir(outDir)

  let baseDir =
    if outDir.len > 0:
      outDir & "/"
    else:
      ""
  let configPath = baseDir & libName & "Config.cmake"
  let versionPath = baseDir & libName & "ConfigVersion.cmake"

  let upperName = libName.toUpperAscii().replace("-", "_")
  let nsName = libName # same as IMPORTED namespace prefix

  # ---------------- ConfigVersion.cmake ----------------
  # Hand-rolled SameMajorVersion logic so consumers don't need to invoke
  # CMakePackageConfigHelpers — the file is self-contained.
  let semverParts = version.split('.')
  let pkgMajor =
    if semverParts.len >= 1:
      semverParts[0]
    else:
      "0"
  var versionFile = ""
  versionFile.add(
    "# Auto-generated by brokers/api_codegen_cmake.nim — do not edit.\n"
  )
  versionFile.add("set(PACKAGE_VERSION \"" & version & "\")\n\n")
  versionFile.add("if(PACKAGE_FIND_VERSION VERSION_EQUAL PACKAGE_VERSION)\n")
  versionFile.add("  set(PACKAGE_VERSION_EXACT TRUE)\n")
  versionFile.add("endif()\n\n")
  versionFile.add(
    "if(NOT PACKAGE_FIND_VERSION OR PACKAGE_FIND_VERSION VERSION_LESS_EQUAL PACKAGE_VERSION)\n"
  )
  versionFile.add("  set(PACKAGE_VERSION_COMPATIBLE FALSE)\n")
  versionFile.add(
    "  if(NOT PACKAGE_FIND_VERSION OR \"${PACKAGE_FIND_VERSION_MAJOR}\" STREQUAL \"" &
      pkgMajor & "\")\n"
  )
  versionFile.add("    set(PACKAGE_VERSION_COMPATIBLE TRUE)\n")
  versionFile.add("  endif()\n")
  versionFile.add("else()\n")
  versionFile.add("  set(PACKAGE_VERSION_COMPATIBLE FALSE)\n")
  versionFile.add("endif()\n")

  try:
    writeFile(versionPath, versionFile)
  except IOError:
    discard # keep raises:[] — codegen errors shouldn't crash compilation

  # ---------------- Config.cmake ----------------
  var cfg = ""
  cfg.add("# Auto-generated by brokers/api_codegen_cmake.nim — do not edit.\n")
  cfg.add("# CMake package for the '" & libName & "' broker FFI library.\n")
  cfg.add("#\n")
  cfg.add("# Provides:\n")
  cfg.add(
    "#   " & nsName & "::" & libName & "       — IMPORTED SHARED library + C headers\n"
  )
  if hasCpp:
    cfg.add(
      "#   " & nsName & "::" & libName &
        "_cpp   — INTERFACE for C++ consumers (C++20)\n"
    )
    if cborMode:
      cfg.add(
        "#       (depends on jsoncons; set " & upperName &
          "_JSONCONS_INCLUDE_DIR to override discovery)\n"
      )
  cfg.add("\n")

  cfg.add("cmake_minimum_required(VERSION 3.16)\n\n")

  cfg.add(
    "get_filename_component(_" & libName &
      "_pkg_dir \"${CMAKE_CURRENT_LIST_DIR}\" ABSOLUTE)\n\n"
  )

  # Resolve platform-specific shared library filename.
  cfg.add("if(WIN32)\n")
  cfg.add("  set(_" & libName & "_shared_name \"" & libName & ".dll\")\n")
  cfg.add("  set(_" & libName & "_import_name \"" & libName & ".lib\")\n")
  cfg.add("elseif(APPLE)\n")
  cfg.add("  set(_" & libName & "_shared_name \"lib" & libName & ".dylib\")\n")
  cfg.add("else()\n")
  cfg.add("  set(_" & libName & "_shared_name \"lib" & libName & ".so\")\n")
  cfg.add("endif()\n\n")

  cfg.add(
    "set(_" & libName & "_shared_path \"${_" & libName & "_pkg_dir}/${_" & libName &
      "_shared_name}\")\n"
  )
  cfg.add("if(NOT EXISTS \"${_" & libName & "_shared_path}\")\n")
  cfg.add(
    "  message(FATAL_ERROR \"" & libName & ": shared library not found at '${_" & libName &
      "_shared_path}'.\")\n"
  )
  cfg.add("endif()\n\n")

  cfg.add(
    "set(_" & libName & "_header_path \"${_" & libName & "_pkg_dir}/" & libName &
      ".h\")\n"
  )
  cfg.add("if(NOT EXISTS \"${_" & libName & "_header_path}\")\n")
  cfg.add(
    "  message(FATAL_ERROR \"" & libName & ": C header not found at '${_" & libName &
      "_header_path}'.\")\n"
  )
  cfg.add("endif()\n\n")

  # IMPORTED SHARED target — the C-level surface. Carries headers + library.
  cfg.add("if(NOT TARGET " & nsName & "::" & libName & ")\n")
  cfg.add("  add_library(" & nsName & "::" & libName & " SHARED IMPORTED)\n")
  cfg.add("  set_target_properties(" & nsName & "::" & libName & " PROPERTIES\n")
  cfg.add("    IMPORTED_LOCATION \"${_" & libName & "_shared_path}\"\n")
  cfg.add("    INTERFACE_INCLUDE_DIRECTORIES \"${_" & libName & "_pkg_dir}\"\n")
  cfg.add("  )\n")
  cfg.add("  if(WIN32)\n")
  cfg.add(
    "    set(_" & libName & "_import_path \"${_" & libName & "_pkg_dir}/${_" & libName &
      "_import_name}\")\n"
  )
  cfg.add("    if(EXISTS \"${_" & libName & "_import_path}\")\n")
  cfg.add(
    "      set_target_properties(" & nsName & "::" & libName &
      " PROPERTIES IMPORTED_IMPLIB \"${_" & libName & "_import_path}\")\n"
  )
  cfg.add("    endif()\n")
  cfg.add("  endif()\n")
  cfg.add("endif()\n\n")

  if hasCpp:
    # INTERFACE target for C++ consumers — pulls in the C target, requires
    # C++20, and (CBOR mode) wires jsoncons.
    cfg.add("if(NOT TARGET " & nsName & "::" & libName & "_cpp)\n")
    cfg.add("  add_library(" & nsName & "::" & libName & "_cpp INTERFACE IMPORTED)\n")
    cfg.add(
      "  set_property(TARGET " & nsName & "::" & libName &
        "_cpp PROPERTY INTERFACE_LINK_LIBRARIES " & nsName & "::" & libName & ")\n"
    )
    cfg.add(
      "  set_property(TARGET " & nsName & "::" & libName &
        "_cpp PROPERTY INTERFACE_COMPILE_FEATURES cxx_std_20)\n"
    )

    if cborMode:
      cfg.add("\n")
      cfg.add("  # jsoncons (header-only) is required by the CBOR-mode C++ wrapper.\n")
      cfg.add("  if(NOT DEFINED " & upperName & "_JSONCONS_INCLUDE_DIR)\n")
      cfg.add(
        "    find_path(" & upperName & "_JSONCONS_INCLUDE_DIR\n" &
          "      NAMES jsoncons/json.hpp\n" & "      PATHS\n" & "        \"${_" & libName &
          "_pkg_dir}/../../vendor/jsoncons/include\"\n" & "        \"${_" & libName &
          "_pkg_dir}/../vendor/jsoncons/include\"\n" & "        \"${_" & libName &
          "_pkg_dir}/vendor/jsoncons/include\"\n" &
          "      DOC \"Path to the jsoncons header-only library (root containing 'jsoncons/json.hpp').\"\n" &
          "    )\n"
      )
      cfg.add("  endif()\n")
      cfg.add("  if(NOT " & upperName & "_JSONCONS_INCLUDE_DIR)\n")
      cfg.add(
        "    message(FATAL_ERROR \"" & libName &
          " (CBOR mode): jsoncons headers not found. Install jsoncons or set " &
          upperName & "_JSONCONS_INCLUDE_DIR.\")\n"
      )
      cfg.add("  endif()\n")
      cfg.add(
        "  set_property(TARGET " & nsName & "::" & libName &
          "_cpp APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES \"${" & upperName &
          "_JSONCONS_INCLUDE_DIR}\")\n"
      )
    cfg.add("endif()\n\n")

  cfg.add("set(" & libName & "_FOUND TRUE)\n")
  cfg.add("set(" & libName & "_VERSION \"" & version & "\")\n")
  cfg.add("set(" & libName & "_LIBRARY \"${_" & libName & "_shared_path}\")\n")
  cfg.add("set(" & libName & "_INCLUDE_DIR \"${_" & libName & "_pkg_dir}\")\n")

  try:
    writeFile(configPath, cfg)
  except IOError:
    discard
