## Generated C header for the CBOR FFI surface.
##
## Unlike the native codegen path (which accumulates per-request structs
## into `gApiHeaderDeclarations`), the CBOR ABI is fixed: every library
## exposes the same eight functions plus one typedef. The only per-library
## variation is the symbol prefix and the documented sets of supported
## apiNames / eventNames, which we emit as comment blocks for human
## readers and language wrappers that aren't using the runtime discovery
## API.

{.push raises: [].}

import std/[macros, os, strutils]
import ./api_common

# ---------------------------------------------------------------------------
# C header emission
# ---------------------------------------------------------------------------

{.pop.}

proc generateCborCHeaderFile*(
    outDir: string,
    libName: string,
    version: string,
    requestApiNames: seq[string],
    eventApiNames: seq[string],
) {.compileTime, raises: [].} =
  ## Writes the fixed-shape C header for a CBOR-mode library.
  ensureGeneratedOutputDir(outDir)

  let guardName = libName.toUpperAscii().replace("-", "_") & "_H"
  let headerPath =
    if outDir.len > 0:
      outDir & "/" & libName & ".h"
    else:
      libName & ".h"
  let p = libName & "_"

  var h = "/* Generated by nim-brokers CBOR FFI codegen — do not edit. */\n"
  h.add("#ifndef " & guardName & "\n")
  h.add("#define " & guardName & "\n\n")
  h.add("#include <stdint.h>\n")
  h.add("#include <stdbool.h>\n")
  h.add("#include <stddef.h>\n\n")
  h.add("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")

  h.add("/* ----------------------------------------------------------------\n")
  h.add(" * Library identity\n")
  h.add(" * ---------------------------------------------------------------- */\n\n")
  h.add(
    "/* Returns a NUL-terminated semver string for this library build (\"" & version &
      "\").\n" & " * The returned pointer is owned by the library — do NOT free. */\n"
  )
  h.add("const char* " & p & "version(void);\n\n")

  h.add("/* ----------------------------------------------------------------\n")
  h.add(" * Lifecycle\n")
  h.add(" * ---------------------------------------------------------------- */\n\n")
  h.add(
    "/* Initialise the Nim runtime and per-thread foreign GC state.\n" &
      " * Idempotent; safe to call from any thread before other entry points. */\n"
  )
  h.add("void " & p & "initialize(void);\n\n")
  h.add(
    "/* Create a new context. Returns the context id (>0 on success), or\n" &
      " * 0 on failure with *errOut populated by a Nim-allocated error\n" &
      " * message that the caller MUST free with " & p & "freeBuffer. */\n"
  )
  h.add("uint32_t " & p & "createContext(char** errOut);\n\n")
  h.add(
    "/* Tear down a context. Returns 0 on success, -1 if the context was\n" &
      " * not found or already shut down. */\n"
  )
  h.add("int32_t " & p & "shutdown(uint32_t ctx);\n\n")
  h.add(
    "/* reduced-A: release a sub-instance created by a create-instance request.\n" &
      " * Drops that ctx's request providers + event listeners on the processing\n" &
      " * thread; the Nim instance is then reclaimed by the GC. Idempotent and\n" &
      " * safe on an unknown/already-released ctx. Returns 0 on success. */\n"
  )
  h.add("int32_t " & p & "releaseInstance(uint32_t ctx);\n\n")

  h.add("/* ----------------------------------------------------------------\n")
  h.add(" * Buffer ownership\n")
  h.add(" *\n")
  h.add(" * Every void* crossing this ABI is allocated by Nim and freed by\n")
  h.add(" * Nim. Callers obtain inbound request buffers via " & p & "allocBuffer,\n")
  h.add(" * fill them with CBOR, and pass them into " & p & "call (which frees\n")
  h.add(" * them before returning). Outbound response and error buffers are\n")
  h.add(" * allocated by the library and the caller frees them with\n")
  h.add(" * " & p & "freeBuffer.\n")
  h.add(" * ---------------------------------------------------------------- */\n\n")
  h.add(
    "/* Allocate a Nim-owned buffer of `size` bytes. Returns NULL on size\n" &
      " * <= 0, size > 64 MiB, or allocation failure. */\n"
  )
  h.add("void* " & p & "allocBuffer(int32_t size);\n\n")
  h.add("/* Free a buffer previously returned by " & p & "allocBuffer or by an\n")
  h.add(" * out-parameter from " & p & "call / " & p & "createContext. NULL is a\n")
  h.add(" * no-op. */\n")
  h.add("void " & p & "freeBuffer(void* buf);\n\n")

  h.add("/* ----------------------------------------------------------------\n")
  h.add(" * Sync request gate\n")
  h.add(" *\n")
  h.add(" * Returns:\n")
  h.add(" *   0  — success; *respBufOut holds the CBOR response envelope\n")
  h.add(" *   -1 — respBufOut or respLenOut is NULL\n")
  h.add(" *   -2 — apiName is NULL\n")
  h.add(" *   -3 — reqLen is negative or exceeds 64 MiB\n")
  h.add(" *   -4 — apiName is unknown; *respBufOut holds a UTF-8 message\n")
  h.add(" *   -10 — internal dispatch failure\n")
  h.add(" * ---------------------------------------------------------------- */\n\n")
  h.add(
    "int32_t " & p & "call(uint32_t ctx,\n" &
      "                       const char* apiName,\n" &
      "                       const void* reqBuf, int32_t reqLen,\n" &
      "                       void** respBufOut, int32_t* respLenOut);\n\n"
  )

  h.add("/* ----------------------------------------------------------------\n")
  h.add(" * Event subscription\n")
  h.add(" *\n")
  h.add(" * Subscribe with cb == NULL probes whether the eventName is\n")
  h.add(" * supported by this library version: returns 1 (sentinel) when\n")
  h.add(" * supported, 0 when not. Real subscription handles are >= 2.\n")
  h.add(" *\n")
  h.add(" * Unsubscribe returns:\n")
  h.add(" *    0 — success\n")
  h.add(" *   -1 — eventName is NULL\n")
  h.add(" *   -2 — no subscriptions registered for (ctx, eventName)\n")
  h.add(" *   -3 — handle not found in the subscription list\n")
  h.add(" *\n")
  h.add(" * Pass handle == 0 to remove every subscription for (ctx, eventName).\n")
  h.add(" * ---------------------------------------------------------------- */\n\n")
  h.add(
    "typedef void (*" & p & "event_cb_t)(uint32_t ctx,\n" &
      "                                       const char* eventName,\n" &
      "                                       const void* payloadBuf,\n" &
      "                                       int32_t payloadLen,\n" &
      "                                       void* userData);\n\n"
  )
  h.add(
    "uint64_t " & p & "subscribe(uint32_t ctx,\n" &
      "                            const char* eventName,\n" &
      "                            " & p & "event_cb_t cb,\n" &
      "                            void* userData);\n\n"
  )
  h.add(
    "int32_t " & p & "unsubscribe(uint32_t ctx,\n" &
      "                              const char* eventName,\n" &
      "                              uint64_t handle);\n\n"
  )

  h.add("/* ----------------------------------------------------------------\n")
  h.add(" * Discovery API\n")
  h.add(" *\n")
  h.add(" * Both functions allocate the response with " & p & "allocBuffer; the\n")
  h.add(" * caller frees it via " & p & "freeBuffer.\n")
  h.add(" *\n")
  h.add(" * " & p & "listApis returns a JSON-encoded ApiList string:\n")
  h.add(" *   {\"libName\": \"...\", \"requests\": [...], \"events\": [...]}\n")
  h.add(" *\n")
  h.add(" * " & p & "getSchema returns a JSON-encoded LibraryDescriptor string (full\n")
  h.add(" * schema including the embedded CDDL text). See <" & libName & ".cddl>\n")
  h.add(" * for the static schema.\n")
  h.add(" *\n")
  h.add(" * The response buffer is a UTF-8 JSON string (not null-terminated).\n")
  h.add(" *\n")
  h.add(" * Returns 0 on success, -1 if any out-pointer is NULL.\n")
  h.add(" * ---------------------------------------------------------------- */\n\n")
  h.add("int32_t " & p & "listApis(void** respBufOut, int32_t* respLenOut);\n\n")
  h.add("int32_t " & p & "getSchema(void** respBufOut, int32_t* respLenOut);\n\n")

  if requestApiNames.len > 0 or eventApiNames.len > 0:
    h.add("/* ----------------------------------------------------------------\n")
    h.add(" * Documented apiNames\n")
    h.add(" * ---------------------------------------------------------------- */\n\n")
    if requestApiNames.len > 0:
      h.add("/* Requests (pass these as `apiName` to " & p & "call):\n")
      for n in requestApiNames:
        h.add(" *   \"" & n & "\"\n")
      h.add(" */\n\n")
    if eventApiNames.len > 0:
      h.add("/* Events (pass these as `eventName` to " & p & "subscribe):\n")
      for n in eventApiNames:
        h.add(" *   \"" & n & "\"\n")
      h.add(" */\n\n")

  h.add("#ifdef __cplusplus\n}\n#endif\n\n")
  h.add("#endif /* " & guardName & " */\n")

  try:
    writeFile(headerPath, h)
  except IOError:
    error(
      "Failed to write generated CBOR C header '" & headerPath & "': " &
        getCurrentExceptionMsg()
    )

{.push raises: [].}
{.pop.}
