## Broker macro debug-dump helper
## ===============================
## Active when client code compiles with `-d:brokerDebug`. The broker
## macros call `writeBrokerDebug(...)` instead of (or in addition to)
## `echo result.repr`, dumping the generated Nim AST — rendered back
## to Nim source — into per-broker files for offline examination.
##
## Output layout (default):
##
##   build/broker_debug/
##     ├── InitializeRequest__RequestBrokerApi.gen.nim
##     ├── ShutdownRequest__RequestBrokerApi.gen.nim
##     ├── DeviceStatusChanged__EventBrokerApi.gen.nim
##     ├── PerfData__RequestBrokerMt.gen.nim
##     ├── …
##     └── mylib__BrokerLibrary.gen.nim   ← `registerBrokerLibrary`
##                                          (FFI C-ABI surface +
##                                           courier/lifecycle plumbing)
##
## Override the directory with `-d:brokerDebugDir=<path>`. The
## directory is created on demand. Files are overwritten — stale
## entries from prior builds are NOT auto-cleaned (delete the dir
## before a build if you want a fresh snapshot).
##
## To preserve the historical "echo result.repr" behaviour alongside
## the file dump, add `-d:brokerDebugStdout`. By default the dump is
## file-only so the build log isn't drowned in generated Nim.
##
## The helper is a `{.compileTime.}` proc — it runs in the Nim VM
## during macro expansion, the same way the C++/Python/Rust/Go
## wrapper codegens write their output files.

{.push raises: [].}

import std/[macros, os, strutils]

const brokerDebugDirOverride {.strdefine: "brokerDebugDir".}: string = ""

proc brokerDebugDir*(): string {.compileTime.} =
  ## Directory under which dump files are written. Override via
  ## `-d:brokerDebugDir=<path>`.
  if brokerDebugDirOverride.len > 0: brokerDebugDirOverride else: "build/broker_debug"

proc sanitizeFileNamePart(s: string): string {.compileTime.} =
  ## Coerce `s` to a portable filename fragment. Conservative —
  ## anything outside `[A-Za-z0-9_-]` becomes `_`.
  result = newStringOfCap(s.len)
  for c in s:
    if c in {'a' .. 'z', 'A' .. 'Z', '0' .. '9', '_', '-'}:
      result.add(c)
    else:
      result.add('_')

proc writeBrokerDebug*(
    role: string, typeName: string, generated: NimNode, header: string = ""
) {.compileTime.} =
  ## Dump the macro-generated AST for one broker (or the
  ## `registerBrokerLibrary` output) into a per-broker file under
  ## `brokerDebugDir()`.
  ##
  ## - `role`    — e.g. "RequestBrokerApi" / "EventBrokerMt" /
  ##               "BrokerLibrary". Used in the filename suffix and
  ##               in the file header.
  ## - `typeName` — the broker type name (or library name for
  ##                `BrokerLibrary`). Used as the filename stem.
  ## - `generated` — the macro's `result` NimNode; its `.repr` is
  ##                 written verbatim after a small comment header.
  ## - `header`   — optional one-line context note (e.g.
  ##                "apiName='initialize_request'").
  ##
  ## Errors are reported via `echo` and the proc returns; we do NOT
  ## raise into the compilation. A failed dump is a diagnostic loss,
  ## not a build failure.
  let dir = brokerDebugDir()
  try:
    createDir(dir)
  except OSError as e:
    echo "[brokers/debug] createDir('", dir, "') failed: ", e.msg, " — skipping dump."
    return
  except IOError as e:
    echo "[brokers/debug] createDir('", dir, "') failed: ", e.msg, " — skipping dump."
    return
  except CatchableError as e:
    echo "[brokers/debug] createDir('", dir, "') failed: ", e.msg, " — skipping dump."
    return

  let safeName = sanitizeFileNamePart(typeName)
  let safeRole = sanitizeFileNamePart(role)
  let path = dir & "/" & safeName & "__" & safeRole & ".gen.nim"

  var s = newStringOfCap(4096)
  s.add("## Auto-generated by nim-brokers macro expansion under -d:brokerDebug.\n")
  s.add("## DO NOT EDIT — this file reflects the AST the macro emits,\n")
  s.add("## rendered back to Nim source for offline examination.\n")
  s.add("##\n")
  s.add("## Role:   " & role & "\n")
  s.add("## Type:   " & typeName & "\n")
  if header.len > 0:
    s.add("## Notes:  " & header & "\n")
  s.add("##\n")
  s.add("## Open in your editor or pipe through `nph` for nicer formatting.\n\n")
  s.add(generated.repr)
  if not s.endsWith("\n"):
    s.add("\n")

  try:
    writeFile(path, s)
  except IOError as e:
    echo "[brokers/debug] writeFile('", path, "') failed: ", e.msg

{.pop.}
