name: build-health

on:
  workflow_call:

env:
  NIM_VERSION: '2.2.6'
  NIMBLE_VERSION: '0.24.1'

jobs:
  build-health:
    name: "Build health"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nim ${{ env.NIM_VERSION }}
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ env.NIM_VERSION }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install nimble deps
        uses: ./.github/actions/nimble-deps
        with:
          nimble-version: ${{ env.NIMBLE_VERSION }}
          nim-version: ${{ env.NIM_VERSION }}

      - uses: ./.github/actions/check-build-health
