name: build-health

on:
  workflow_call:

jobs:
  build-health:
    name: "Build health"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install nimble deps
        uses: ./.github/actions/nimble-deps

      - uses: ./.github/actions/check-build-health

      - name: Audit installed deps
        run: make audit-deps
