{
 "title": "Nim-Waku Single Node",
 "description": "Metrics for Waku nodes written in Nim",
 "time": { "from": "now-10d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "host", "label": "Hostname regex", "query": "node-.*" },
   {
    "name": "fleet",
    "label": "Fleet name",
    "query": {
     "query": "label_values(libp2p_peers, fleet)"
    }
   },
   {
    "name": "dc",
    "label": "Data Center",
    "query": {
     "query": "label_values(libp2p_peers, datacenter)"
    }
   }
  ]
 },
 "panels": [
  { "title": "At a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Libp2p PubSub Peers",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_pubsub_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
     "legendFormat": "{{fleet}}: {{datacenter}}"
    }
   ]
  },
  {
   "title": "Node start times (UTC)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance)(netdata_cpu_cpu_percentage_average{dimension=\"user\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "(waku_version{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_version{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node is Reachable (Experimental)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "libp2p_autonat_reachability_confidence{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", reachability=\"Reachable\"}",
     "legendFormat": "{{instance}}:{{reachability}}"
    }
   ]
  },
  {
   "title": "Node is NotReachable (Experimental)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "libp2p_autonat_reachability_confidence{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", reachability=\"NotReachable\"}",
     "legendFormat": "{{instance}}:{{reachability}}"
    }
   ]
  },
  {
   "title": "Inbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", direction=\"in\"}[$__rate_interval])",
     "legendFormat": "{{instance}}:{{direction}}"
    }
   ]
  },
  {
   "title": "Outbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", direction=\"out\"}[$__rate_interval])",
     "legendFormat": "{{instance}}:{{direction}}"
    }
   ]
  },
  {
   "title": "Messages (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "((increase(waku_node_messages_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1m]) or increase(logos_delivery_node_messages_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1m])))",
     "legendFormat": "{{type}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Waku Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by (type)((increase(waku_peers_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or increase(logos_delivery_peers_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval])))",
     "legendFormat": "peer {{type}}"
    },
    {
     "expr": "sum by (type)((increase(waku_store_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or increase(logos_delivery_store_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval])))",
     "legendFormat": "store {{type}}"
    },
    {
     "expr": "sum by (type)((increase(waku_node_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or increase(logos_delivery_node_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval])))",
     "legendFormat": "node {{type}}"
    }
   ]
  },
  {
   "title": "Total Content Topics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "count(count by (contentTopic)((waku_node_messages_total or logos_delivery_node_messages_total)))",
     "legendFormat": "content topics"
    }
   ]
  },
  {
   "title": "Waku version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "(waku_version{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_version{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
     "legendFormat": "{{instance}}:{{version}}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Waku Node Filters",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "waku_node_filters{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Waku Node Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "(waku_node_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_node_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
     "legendFormat": "{{type}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Pubsub Topics",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "libp2p_pubsub_topics {instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
     "legendFormat": "Topics: {{instance}}"
    },
    {
     "expr": "libp2p_pubsub_subscriptions_total {instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
     "legendFormat": "Subscriptions: {{instance}}"
    },
    {
     "expr": "libp2p_pubsub_unsubscriptions_total {instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
     "legendFormat": "Unsubscriptions: {{instance}}"
    }
   ]
  },
  {
   "title": "LibP2P PubSub Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(libp2p_pubsub_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LibP2P Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(libp2p_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peer Store Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(waku_peer_store_size{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_peer_store_size{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LibP2P Open Streams",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type)(libp2p_open_streams{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "LibP2P Validations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_pubsub_validation_success_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
     "legendFormat": "success {{instance}}"
    },
    {
     "expr": "libp2p_pubsub_validation_failure_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
     "legendFormat": "failure {{instance}}"
    },
    {
     "expr": "libp2p_pubsub_validation_ignore_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
     "legendFormat": "ignore {{instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(process_open_fds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LibP2P Dials",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_total_dial_attempts_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
     "legendFormat": "Attempts: {{instance}}"
    },
    {
     "expr": "libp2p_failed_dials_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
     "legendFormat": "Failed: {{instance}}"
    },
    {
     "expr": "libp2p_successful_dials_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
     "legendFormat": "Successful: {{instance}}"
    }
   ]
  },
  {
   "title": "Nim Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
     "legendFormat": "Nim total memory: {{instance}}"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
     "legendFormat": "Nim occupied memory: {{instance}}"
    },
    {
     "expr": "nim_gc_heap_instance_occupied_summed_bytes{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
     "legendFormat": "Nim total heap: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance)(netdata_cpu_cpu_percentage_average{dimension=\"user\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
     "legendFormat": "{{instance}}  {{type_name}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance)(process_virtual_memory_bytes{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance)(process_resident_memory_bytes{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bridge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bridge (10m rate)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "targets": [
      {
       "expr": "increase(waku_bridge_transfers_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[10m])",
       "legendFormat": "{{fleet}} : {{type}}"
      },
      {
       "expr": "increase(envelopes_valid_total{instance=~\"bridge*[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[10m])",
       "legendFormat": "{{fleet}} : v1_envelopes"
      },
      {
       "expr": "(increase(waku_node_messages_total{instance=~\"bridge*[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[10m]) or increase(logos_delivery_node_messages_total{instance=~\"bridge*[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[10m]))",
       "legendFormat": "{{fleet}} : v2_messages"
      },
      {
       "expr": "increase(envelopes_dropped_total{instance=~\"bridge*[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[10m])",
       "legendFormat": "{{fleet}} : v1_envelopes_dropped ({{reason}})"
      }
     ]
    },
    {
     "title": "Connected Peers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "targets": [
      {
       "expr": "connected_peers{instance=~\"bridge*[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "v1_connected_peers"
      },
      {
       "expr": "libp2p_pubsub_peers{instance=~\"bridge*[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "v2_connected_peers"
      }
     ]
    }
   ]
  },
  {
   "title": "Store/Archive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "collapsed": true,
   "panels": [
    {
     "title": "Waku Store Peers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "(waku_store_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_store_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Waku Archive Messages",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 99 },
     "targets": [
      {
       "expr": "waku_store_messages{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "{{type}}: {{instance}}"
      },
      {
       "expr": "(waku_archive_messages{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_archive_messages{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{type}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Waku Store Queries (1m rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "(increase(waku_store_queries_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1m]) or increase(logos_delivery_store_queries_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Waku Archive Errors (1m rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 105 },
     "targets": [
      {
       "expr": "sum by (type)((increase(waku_archive_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[1m]) or increase(logos_delivery_archive_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[1m])))",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum by (type)((increase(waku_store_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[1m]) or increase(logos_delivery_store_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[1m])))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Waku Archive Query Duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "sum((increase(waku_archive_query_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or increase(logos_delivery_archive_query_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]))) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Waku Archive Insert Duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
     "targets": [
      {
       "expr": "sum((increase(waku_archive_insert_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or increase(logos_delivery_archive_insert_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]))) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "collapsed": true,
   "panels": [
    {
     "title": "Waku Filter Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "(waku_filter_requests_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_filter_requests_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{type}} : {{instance}}"
      }
     ]
    },
    {
     "title": "Waku Filter Subscriptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 135 },
     "targets": [
      {
       "expr": "(waku_filter_subscriptions{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_filter_subscriptions{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Waku Filter Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 135 },
     "targets": [
      {
       "expr": "(waku_filter_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_filter_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{type}} : {{instance}}"
      }
     ]
    },
    {
     "title": "Waku Filter Request Duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
     "targets": [
      {
       "expr": "sum((increase(waku_filter_request_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or increase(logos_delivery_filter_request_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]))) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Waku Filter Handle Message Duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
     "targets": [
      {
       "expr": "sum((increase(waku_filter_handle_message_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or increase(logos_delivery_filter_handle_message_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]))) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filter (Legacy)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Waku Filter Peers",
     "type": "timeseries",
     "description": "Waku Filter Peers",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
     "targets": [
      {
       "expr": "(waku_filter_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_filter_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Waku Filter Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
     "targets": [
      {
       "expr": "(waku_filter_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_filter_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{type}}: {{instance}}"
      },
      {
       "expr": "waku_legacy_filter_errors{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "{{type}} : {{instance}}"
      }
     ]
    },
    {
     "title": "Waku Filter Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
     "targets": [
      {
       "expr": "waku_filter_messages{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "{{type}} : {{instance}}"
      },
      {
       "expr": "waku_legacy_filter_messages{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "{{type}} : {{instance}}"
      }
     ]
    },
    {
     "title": "Waku Filter Subscribers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 157 },
     "targets": [
      {
       "expr": "waku_filter_subscribers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "waku_legacy_filter_subscribers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Lightpush",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "collapsed": true,
   "panels": [
    {
     "title": "Waku Lightpush Peers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
     "targets": [
      {
       "expr": "(waku_lightpush_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_lightpush_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Waku Lightpush Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
     "targets": [
      {
       "expr": "(waku_lightpush_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_lightpush_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{type}}: {[instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages/second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "((increase(waku_node_messages_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1m]) or increase(logos_delivery_node_messages_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1m])))/60",
       "legendFormat": "{{fleet}}_{{datacenter}}"
      }
     ]
    },
    {
     "title": "Average msg size (kBytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "(waku_histogram_message_size_sum{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_histogram_message_size_sum{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})/(waku_histogram_message_size_count{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_histogram_message_size_count{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
       "legendFormat": "{{fleet}}_{{datacenter}}"
      }
     ]
    },
    {
     "title": "Message distrubution %/kBytes (Last Hour)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(rate(waku_histogram_message_size_bucket{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1h]) or rate(logos_delivery_histogram_message_size_bucket{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1h]))/scalar((rate(waku_histogram_message_size_count{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1h]) or rate(logos_delivery_histogram_message_size_count{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1h])))*100",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Connected Peers per Protocol",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(waku_connected_peers{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_connected_peers{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
       "legendFormat": "Direction:{{direction}} {{protocol}}"
      }
     ]
    },
    {
     "title": "Connected Streams per Protocol",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(waku_streams_peers{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_streams_peers{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
       "legendFormat": "Direction:{{direction}} {{protocol}}"
      }
     ]
    }
   ]
  },
  { "title": "RLN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Invalid Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "(waku_rln_invalid_messages_total_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_rln_invalid_messages_total_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
     "legendFormat": "{{type}}_{{datacenter}}"
    }
   ]
  },
  {
   "title": "Valid RLN Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "(waku_rln_valid_messages_total_count{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_rln_valid_messages_total_count{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
     "legendFormat": "{{__name__}}_{{datacenter}}"
    }
   ]
  },
  {
   "title": "Spam messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "(waku_rln_spam_messages_total_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_rln_spam_messages_total_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
     "legendFormat": "{{__name__}}_{{datacenter}}"
    }
   ]
  },
  {
   "title": "Proof Verification (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "targets": [
    {
     "expr": "(waku_rln_proof_verification_duration_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_rln_proof_verification_duration_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
     "legendFormat": "{{__name__}}_{{datacenter}}"
    }
   ]
  },
  {
   "title": "RLN Memberships",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "(waku_rln_number_registered_memberships{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_rln_number_registered_memberships{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
     "legendFormat": "{{__name__}}_{{datacenter}}"
    }
   ]
  }
 ]
}