{
 "title": "Nim-Waku V2",
 "description": "Metrics for Waku nodes written in Nim",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "host", "label": "Hostname regex", "query": ".*,node-.*,boot-.*,store-.*" },
   {
    "name": "fleet",
    "label": "Fleet name",
    "query": {
     "query": "label_values(libp2p_peers, fleet)"
    }
   },
   { "name": "dc", "label": "Data Center", "query": { "query": "label_values(libp2p_peers, dc)" } }
  ]
 },
 "panels": [
  {
   "title": "At a glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Libp2p PubSub Peers",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "libp2p_pubsub_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "{{fleet}}: {{datacenter}}"
      }
     ]
    },
    {
     "title": "Node start times (UTC)",
     "type": "stat",
     "gridPos": { "h": 10, "w": 7, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} * 1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (instance)(netdata_cpu_cpu_percentage_average{dimension=\"user\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Version",
     "type": "table",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
     "targets": [
      {
       "expr": "(waku_version{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_version{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node is Reachable (Experimental)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 290 },
     "targets": [
      {
       "expr": "libp2p_autonat_reachability_confidence{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", reachability=\"Reachable\"}",
       "legendFormat": "{{instance}}:{{reachability}}"
      }
     ]
    },
    {
     "title": "Node is NotReachable (Experimental)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 290 },
     "targets": [
      {
       "expr": "libp2p_autonat_reachability_confidence{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", reachability=\"NotReachable\"}",
       "legendFormat": "{{instance}}:{{reachability}}"
      }
     ]
    },
    {
     "title": "Inbound Traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 299 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(libp2p_network_bytes_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", direction=\"in\"}[$__rate_interval])",
       "legendFormat": "{{instance}}:{{direction}}"
      }
     ]
    },
    {
     "title": "Outbound Traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 299 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(libp2p_network_bytes_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", direction=\"out\"}[$__rate_interval])",
       "legendFormat": "{{instance}}:{{direction}}"
      }
     ]
    },
    {
     "title": "Relay traffic per shard (in) - average of all peers",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 308 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg by(topic, type)((rate(waku_relay_network_bytes_total{direction=\"in\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]) or rate(logos_delivery_relay_network_bytes_total{direction=\"in\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval])))",
       "legendFormat": "{{topic}} - {{type}}"
      }
     ]
    },
    {
     "title": "Relay traffic per shard (out) - average of all peers",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 308 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg by(topic, type)((rate(waku_relay_network_bytes_total{direction=\"out\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]) or rate(logos_delivery_relay_network_bytes_total{direction=\"out\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval])))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "# peers per protocol (in)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 318 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (protocol)((waku_connected_peers{direction=\"In\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_connected_peers{direction=\"In\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}))",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "# peers per protocol (out)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 318 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (protocol)((waku_connected_peers{direction=\"Out\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_connected_peers{direction=\"Out\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}))",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Messages (1m rate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 328 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "((increase(waku_node_messages_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1m]) or increase(logos_delivery_node_messages_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1m])))",
       "legendFormat": "{{type}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Connected Peers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 328 },
     "targets": [
      {
       "expr": "libp2p_pubsub_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "peer {{instance}}"
      }
     ]
    },
    {
     "title": "Total Content Topics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 337 },
     "targets": [
      {
       "expr": "count(count by (contentTopic)((waku_node_messages_total or logos_delivery_node_messages_total)))",
       "legendFormat": "content topics"
      }
     ]
    },
    {
     "title": "Waku Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 337 },
     "targets": [
      {
       "expr": "sum by (type)((increase(waku_peers_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or increase(logos_delivery_peers_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval])))",
       "legendFormat": "peer {{type}}"
      },
      {
       "expr": "sum by (type)((increase(waku_store_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or increase(logos_delivery_store_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval])))",
       "legendFormat": "store {{type}}"
      },
      {
       "expr": "sum by (type)((increase(waku_node_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or increase(logos_delivery_node_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval])))",
       "legendFormat": "node {{type}}"
      }
     ]
    },
    {
     "title": "Waku version",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 346 },
     "targets": [
      {
       "expr": "(waku_version{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_version{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}:{{version}}"
      }
     ]
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Waku Node Filters",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1652 },
     "targets": [
      {
       "expr": "waku_node_filters{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Waku Node Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1652 },
     "targets": [
      {
       "expr": "(waku_node_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_node_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{type}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Pubsub Topics",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2554 },
     "targets": [
      {
       "expr": "libp2p_pubsub_topics {instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
       "legendFormat": "Topics: {{instance}}"
      },
      {
       "expr": "libp2p_pubsub_subscriptions_total {instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
       "legendFormat": "Subscriptions: {{instance}}"
      },
      {
       "expr": "libp2p_pubsub_unsubscriptions_total {instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
       "legendFormat": "Unsubscriptions: {{instance}}"
      }
     ]
    },
    {
     "title": "LibP2P PubSub Peers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2554 },
     "targets": [
      {
       "expr": "sum by (instance)(libp2p_pubsub_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "LibP2P Peers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2560 },
     "targets": [
      {
       "expr": "sum by (instance)(libp2p_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Peer Store Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2560 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(waku_peer_store_size{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_peer_store_size{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "LibP2P Open Streams",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2566 },
     "targets": [
      {
       "expr": "sum by (type)(libp2p_open_streams{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "LibP2P Validations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2566 },
     "targets": [
      {
       "expr": "libp2p_pubsub_validation_success_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
       "legendFormat": "success {{instance}}"
      },
      {
       "expr": "libp2p_pubsub_validation_failure_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
       "legendFormat": "failure {{instance}}"
      },
      {
       "expr": "libp2p_pubsub_validation_ignore_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
       "legendFormat": "ignore {{instance}}"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2572 },
     "targets": [
      {
       "expr": "sum by (instance)(process_open_fds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "LibP2P Dials",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2572 },
     "targets": [
      {
       "expr": "libp2p_total_dial_attempts_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
       "legendFormat": "Attempts: {{instance}}"
      },
      {
       "expr": "libp2p_failed_dials_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
       "legendFormat": "Failed: {{instance}}"
      },
      {
       "expr": "libp2p_successful_dials_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}",
       "legendFormat": "Successful: {{instance}}"
      }
     ]
    },
    {
     "title": "Nim Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2578 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "nim_gc_mem_bytes{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "Nim total memory: {{instance}}"
      },
      {
       "expr": "nim_gc_mem_occupied_bytes{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "Nim occupied memory: {{instance}}"
      },
      {
       "expr": "nim_gc_heap_instance_occupied_summed_bytes{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "Nim total heap: {{instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2578 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance)(netdata_cpu_cpu_percentage_average{dimension=\"user\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap allocation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2584 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "nim_gc_heap_instance_occupied_bytes{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "{{instance}}  {{type_name}}"
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2586 },
     "targets": [
      {
       "expr": "sum by (instance)(process_virtual_memory_bytes{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Resident Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2592 },
     "targets": [
      {
       "expr": "sum by (instance)(process_resident_memory_bytes{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RLN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Generated RLN Proofs",
     "type": "timeseries",
     "description": "total number of proofs generated since the node started",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1653 },
     "targets": [
      {
       "expr": "(waku_rln_total_generated_proofs or logos_delivery_rln_total_generated_proofs)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RLN proofs verified",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1653 },
     "targets": [
      {
       "expr": "(waku_rln_proof_verification_total_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_rln_proof_verification_total_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Remaining RLN Proofs per epoch",
     "type": "timeseries",
     "description": "number of proofs remaining to be generated for the current epoch",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1653 },
     "targets": [
      {
       "expr": "(waku_rln_remaining_proofs_per_epoch or logos_delivery_rln_remaining_proofs_per_epoch)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RLN Proof Generation Time (seconds)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1911 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(waku_rln_proof_generation_duration_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_rln_proof_generation_duration_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RLN Proof verification Time (seconds)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1911 },
     "targets": [
      {
       "expr": "(waku_rln_proof_verification_duration_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_rln_proof_verification_duration_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RLN Proof Generation TIme Changes per epoch ( Entropy )",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1919 },
     "targets": [
      {
       "expr": "(changes(waku_rln_proof_generation_duration_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[14m]) or changes(logos_delivery_rln_proof_generation_duration_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[14m]))",
       "legendFormat": "Proofs generated: {{instance}}"
      }
     ]
    },
    {
     "title": "RLN Message Counter (Invalid & Spam)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1919 },
     "targets": [
      {
       "expr": "(waku_rln_invalid_messages_total_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_rln_invalid_messages_total_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{type}} : {{instance}}"
      },
      {
       "expr": "(waku_rln_spam_messages_total_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_rln_spam_messages_total_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "spam : {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Store/Archive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Waku Store Peers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "(waku_store_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_store_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Waku Archive Messages",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "waku_store_messages{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "{{type}}: {{instance}}"
      },
      {
       "expr": "(waku_archive_messages{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_archive_messages{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{type}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Waku Store Queries (1m rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "(increase(waku_store_queries_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1m]) or increase(logos_delivery_store_queries_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Waku Archive Errors (1m rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum by (type)((increase(waku_archive_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[1m]) or increase(logos_delivery_archive_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[1m])))",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum by (type)((increase(waku_store_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[1m]) or increase(logos_delivery_store_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[1m])))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Time Send Query To DB (sec)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(query_time_secs{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", phase=\"sendQuery\"} or logos_delivery_query_time_secs{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", phase=\"sendQuery\"}) and (deriv(query_time_secs{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", phase=\"sendQuery\"}[1m]) or deriv(logos_delivery_query_time_secs{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", phase=\"sendQuery\"}[1m])) != 0",
       "legendFormat": "{{query}}"
      }
     ]
    },
    {
     "title": "Wait Queries To Finish (sec)",
     "type": "timeseries",
     "description": "Shows the time spent while waiting for feedback from the database. That time includes the database query time plus the time spent waiting for the response from the database.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(query_time_secs{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", phase=\"waitFinish\"} or logos_delivery_query_time_secs{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", phase=\"waitFinish\"}) and (deriv(query_time_secs{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", phase=\"waitFinish\"}[45s]) or deriv(logos_delivery_query_time_secs{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", phase=\"waitFinish\"}[45s])) != 0",
       "legendFormat": "{{query}}"
      }
     ]
    },
    {
     "title": "Store V3 Times details",
     "type": "timeseries",
     "description": "query-db-time: time for DB to complete query\nsend-store-resp-time: time for nwaku to process DB response and forward to the wire",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(waku_store_time_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_store_time_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}) and (deriv(waku_store_time_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[45s]) or deriv(logos_delivery_store_time_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[45s])) != 0",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Store V3 Times wire-to-wire",
     "type": "timeseries",
     "description": "Total time from moment query hits nwaku node to response sent over wire. This represents an aggregation and helps to get an idea of current node's response time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum without (phase) ((waku_store_time_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_store_time_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})\n  unless (changes(waku_store_time_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[45s]) or changes(logos_delivery_store_time_seconds{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[45s])) == 0)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Not-Insert Queries Rate (query/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rate(query_count_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", query!=\"InsertRow\"}[1m]) or rate(logos_delivery_query_count_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", query!=\"InsertRow\"}[1m])) and (rate(query_count_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", query!=\"InsertRowMessagesLookup\"}[1m]) or rate(logos_delivery_query_count_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", query!=\"InsertRowMessagesLookup\"}[1m])) ",
       "legendFormat": "{{query}}"
      }
     ]
    },
    {
     "title": "Insert Queries Rate (insert/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rate(query_count_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", query=\"InsertRow\"}[5m]) or rate(logos_delivery_query_count_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\", query=\"InsertRow\"}[5m]))",
       "legendFormat": "{{query}}"
      }
     ]
    },
    {
     "title": "Waku Archive Query Duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum((increase(waku_archive_query_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or increase(logos_delivery_archive_query_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]))) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Waku Archive Insert Duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "sum((increase(waku_archive_insert_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or increase(logos_delivery_archive_insert_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]))) by (le)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(waku_legacy_archive_insert_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Store v3 protocol traffic (in)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(rate(waku_service_network_bytes_total{service=\"/vac/waku/store-query/3.0.0\", direction=\"in\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]) or rate(logos_delivery_service_network_bytes_total{service=\"/vac/waku/store-query/3.0.0\", direction=\"in\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Store v3 protocol traffic (out)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(rate(waku_service_network_bytes_total{service=\"/vac/waku/store-query/3.0.0\", direction=\"out\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]) or rate(logos_delivery_service_network_bytes_total{service=\"/vac/waku/store-query/3.0.0\", direction=\"out\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Store v3 query request rates",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "(rate(waku_service_requests_total{service =~\"/vac/waku/store-query/3.*\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]) or rate(logos_delivery_service_requests_total{service =~\"/vac/waku/store-query/3.*\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} - {{state}}"
      }
     ]
    }
   ]
  },
  { "title": "Store Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Bytes Exchanged",
   "type": "timeseries",
   "description": "the number of bytes sent and received by the protocols.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum by(direction, protocol) ((total_bytes_exchanged_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_total_bytes_exchanged_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Exchanged",
   "type": "timeseries",
   "description": "the number of messages sent and received by the transfer protocol.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "sum by(direction) ((total_transfer_messages_exchanged_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_total_transfer_messages_exchanged_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of Round-Trips per Reconciliation",
   "type": "bargauge",
   "description": "the number of roundtrips for each reconciliation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) ((reconciliation_roundtrips_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_reconciliation_roundtrips_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of differences per reconciliation.",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) ((reconciliation_differences_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_reconciliation_differences_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Cached",
   "type": "timeseries",
   "description": "The total number of messages cached by nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "(total_messages_cached{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_total_messages_cached{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Filter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "collapsed": true,
   "panels": [
    {
     "title": "Waku Filter Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4479 },
     "targets": [
      {
       "expr": "(rate(waku_filter_requests_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or rate(logos_delivery_filter_requests_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]))",
       "legendFormat": "{{type}} : {{instance}}"
      }
     ]
    },
    {
     "title": "Waku Filter Subscriptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4479 },
     "targets": [
      {
       "expr": "(waku_filter_subscriptions{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_filter_subscriptions{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Waku Filter Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4479 },
     "targets": [
      {
       "expr": "(rate(waku_filter_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or rate(logos_delivery_filter_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]))",
       "legendFormat": "{{type}} : {{instance}}"
      }
     ]
    },
    {
     "title": "Waku Filter Request Duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4487 },
     "targets": [
      {
       "expr": "sum((increase(waku_filter_request_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or increase(logos_delivery_filter_request_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]))) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Waku Filter Handle Message Duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4487 },
     "targets": [
      {
       "expr": "sum((increase(waku_filter_handle_message_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]) or increase(logos_delivery_filter_handle_message_duration_seconds_bucket{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}[$__rate_interval]))) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Filter subscribe request rates",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 4495 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "(rate(waku_service_requests_total{service = \"/vac/waku/filter-subscribe/2.0.0-beta1\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]) or rate(logos_delivery_service_requests_total{service = \"/vac/waku/filter-subscribe/2.0.0-beta1\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} - {{state}}"
      }
     ]
    },
    {
     "title": "Filter protocol message push traffic (out)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 4495 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(rate(waku_service_network_bytes_total{service=\"/vac/waku/filter-push/2.0.0-beta1\", direction=\"out\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]) or rate(logos_delivery_service_network_bytes_total{service=\"/vac/waku/filter-push/2.0.0-beta1\", direction=\"out\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Lightpush",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "panels": [
    {
     "title": "Waku Lightpush Peers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4554 },
     "targets": [
      {
       "expr": "(waku_lightpush_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_lightpush_peers{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Waku Lightpush Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4554 },
     "targets": [
      {
       "expr": "(waku_lightpush_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} or logos_delivery_lightpush_errors_total{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "{{type}}: {[instance}}"
      }
     ]
    },
    {
     "title": "Lightpush request rates",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4562 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "(rate(waku_service_requests_total{service = \"/vac/waku/lightpush/2.0.0-beta1\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]) or rate(logos_delivery_service_requests_total{service = \"/vac/waku/lightpush/2.0.0-beta1\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} . {{state}}"
      }
     ]
    },
    {
     "title": "Lightpush protocol traffic (in)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4562 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(rate(waku_service_network_bytes_total{service=\"/vac/waku/lightpush/2.0.0-beta1\", direction=\"in\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]) or rate(logos_delivery_service_network_bytes_total{service=\"/vac/waku/lightpush/2.0.0-beta1\", direction=\"in\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Peer Exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peer Exchange request rates",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4575 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "(rate(waku_service_requests_total{service = \"/vac/waku/peer-exchange/2.0.0-alpha1\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]) or rate(logos_delivery_service_requests_total{service = \"/vac/waku/peer-exchange/2.0.0-alpha1\", instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} . {{state}}"
      }
     ]
    },
    {
     "title": "Peer Exchange number of sent peers",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4575 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rate(waku_px_peers_sent_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]) or rate(logos_delivery_px_peers_sent_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Peer Exchange errors total",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4587 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance, type) ((waku_px_errors_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_px_errors_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}))",
       "legendFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "Peer Exchange errors",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4587 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rate(waku_px_errors_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]) or rate(logos_delivery_px_errors_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} - {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "Waku Swap Peers",
     "type": "timeseries",
     "description": "number of swap peers",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4600 },
     "targets": [
      {
       "expr": "waku_swap_peers_count{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Waku Swap Account State",
     "type": "timeseries",
     "description": "swap account state for each peer",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4600 },
     "targets": [
      {
       "expr": "sum(waku_peer_swap_account_balance_bucket{le=\"250.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} - ignoring(le) waku_peer_swap_account_balance_bucket{le=\"200.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "250"
      },
      {
       "expr": "sum(waku_peer_swap_account_balance_bucket{le=\"200.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} - ignoring(le) waku_peer_swap_account_balance_bucket{le=\"150.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "200"
      },
      {
       "expr": "sum(waku_peer_swap_account_balance_bucket{le=\"150.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} - ignoring(le) waku_peer_swap_account_balance_bucket{le=\"100.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "150"
      },
      {
       "expr": "sum(waku_peer_swap_account_balance_bucket{le=\"100.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} - ignoring(le) waku_peer_swap_account_balance_bucket{le=\"50.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "100"
      },
      {
       "expr": "sum(waku_peer_swap_account_balance_bucket{le=\"50.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} - ignoring(le) waku_peer_swap_account_balance_bucket{le=\"0.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "50"
      },
      {
       "expr": "sum(waku_peer_swap_account_balance_bucket{le=\"0.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} - ignoring(le) waku_peer_swap_account_balance_bucket{le=\"-50.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "0"
      },
      {
       "expr": "sum(waku_peer_swap_account_balance_bucket{le=\"-50.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} - ignoring(le) waku_peer_swap_account_balance_bucket{le=\"-100.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "-50"
      },
      {
       "expr": "sum(waku_peer_swap_account_balance_bucket{le=\"-100.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} - ignoring(le) waku_peer_swap_account_balance_bucket{le=\"-150.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "-100"
      },
      {
       "expr": "sum(waku_peer_swap_account_balance_bucket{le=\"-150.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"} - ignoring(le) waku_peer_swap_account_balance_bucket{le=\"-200.0\", instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"})",
       "legendFormat": "-150"
      }
     ]
    },
    {
     "title": "Waku Swap Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4600 },
     "targets": [
      {
       "expr": "waku_swap_errors{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\"}",
       "legendFormat": "{{type}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Messages/second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4607 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "((increase(waku_node_messages_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1m]) or increase(logos_delivery_node_messages_total{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1m])))/60",
       "legendFormat": "{{fleet}}_{{datacenter}}"
      }
     ]
    },
    {
     "title": "Average msg size (kBytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4607 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "(waku_histogram_message_size_sum{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_histogram_message_size_sum{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})/(waku_histogram_message_size_count{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_histogram_message_size_count{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
       "legendFormat": "{{fleet}}_{{datacenter}}"
      }
     ]
    },
    {
     "title": "Message distrubution %/kBytes (Last Hour)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4615 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(rate(waku_histogram_message_size_bucket{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1h]) or rate(logos_delivery_histogram_message_size_bucket{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1h]))/scalar((rate(waku_histogram_message_size_count{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1h]) or rate(logos_delivery_histogram_message_size_count{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"}[1h])))*100",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Connected Peers per Protocol",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4623 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(waku_connected_peers{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_connected_peers{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
       "legendFormat": "Direction:{{direction}} {{protocol}}"
      }
     ]
    },
    {
     "title": "Connected Streams per Protocol",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4623 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(waku_streams_peers{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"} or logos_delivery_streams_peers{instance=~\"[[host]].([[dc:pipe]]).([[fleet:pipe]])\"})",
       "legendFormat": "Direction:{{direction}} {{protocol}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk space used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4632 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "netdata_disk_space_GiB_average{instance=~\"[[host]].([[dc:pipe]]).*.([[fleet:pipe]])\",dimension=\"used\", family=\"/data\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}